export const AFGHANISTAN: Record<string, string> = {
	"Afghanistan": "AF",
	"Kabul": "AF",
	"Kandahar": "AF",
	"Herat": "AF",
	"Mazar-i-Sharif": "AF",
	"Kunduz": "AF",
	"Taloqan": "AF",
	"Jalalabad": "AF",
	"Puli Khumri": "AF",
	"Charikar": "AF",
	"Sheberghan": "AF",
	"Ghazni": "AF",
	"Sar-e Pol": "AF",
	"Khost": "AF",
	"Chaghcharan": "AF",
	"Farah": "AF",
	"Pol-e Alam": "AF",
	"Almar": "AF",
	"Faizabad": "AF",
	"Fayzabad-AF": "AF",
	"Zaranj": "AF",
	"Lashkar Gah": "AF",
	"Maymana": "AF",
	"Asadabad": "AF",
	"Maidan Shar": "AF",
	"Bamyan": "AF",
	"Gardez": "AF",
	"Qalat-AF": "AF",
	"Bala Murghab": "AF",
	"Qala i Naw": "AF",
	"Aybak": "AF",
	"Sharan": "AF",
	"Bazarak": "AF",
	"Parun": "AF",
	"Nili": "AF",
	"Mahmud-i-Raqi": "AF",
	"Khanabad": "AF",
	"Spin Boldak": "AF",
	"Andkhoy": "AF",
	"Paghman": "AF",
	"Imam Sahib": "AF",
	"Rustaq": "AF",
	"Qunduz": "AF",
	"Sangin": "AF",
	"Girishk": "AF",
	"Khulm": "AF",
	"Mir Bachakot": "AF",
	"Balkh": "AF",
	"Karukh": "AF",
	"Gurian": "AF",
	"Urgun": "AF",
	"Shindand": "AF"
};
