export const USA = {
	"California": "US",
	"nyc": "US",
	"houston": "US",
	"phoenix": "US",
	"philadelphia": "US",
	"philly": "US",
	"san antonio": "US",
	"san diego": "US",
	"sanjose": "US",
	"fort worth": "US",
	"jacksonville": "US",
	"charlotte": "US",
	"columbus": "US",
	"indianapolis": "US",
	"washington": "US",
	"el paso": "US",
	"nashville": "US",
	"las vegas": "US",
	"vegas": "US",
	"detroit": "US",
	"oklahoma city": "US",
	"memphis": "US",
	"louisville": "US",
	"baltimore": "US",
	"milwaukee": "US",
	"albuquerque": "US",
	"tucson": "US",
	"fresno": "US",
	"sacramento": "US",
	"mesa": "US",
	"kansas city": "US",
	"colorado springs": "US",
	"omaha": "US",
	"raleigh": "US",
	"long beach": "US",
	"virginia beach": "US",
	"oakland": "US",
	"minneapolis": "US",
	"tulsa": "US",
	"tampa": "US",
	"arlington": "US",
	"new orleans": "US",
	"wichita": "US",
	"bakersfield": "US",
	"cleveland": "US",
	"aurora": "US",
	"anaheim": "US",
	"honolulu": "US",
	"santa ana": "US",
	"riverside": "US",
	"corpus christi": "US",
	"lexington": "US",
	"henderson": "US",
	"stockton": "US",
	"st. louis": "US",
	"saint louis": "US",
	"cincinnati": "US",
	"pittsburgh": "US",
	"anchorage": "US",
	"greensboro": "US",
	"plano": "US",
	"lincoln": "US",
	"orlando": "US",
	"irvine": "US",
	"newark": "US",
	"toledo": "US",
	"durham": "US",
	"chula vista": "US",
	"fort wayne": "US",
	"jersey city": "US",
	"st. paul": "US",
	"saint paul": "US",
	"laredo": "US",
	"madison": "US",
	"chandler": "US",
	"buffalo": "US",
	"lubbock": "US",
	"scottsdale": "US",
	"reno": "US",
	"glendale": "US",
	"norfolk": "US",
	"winston-salem": "US",
	"north las vegas": "US",
	"gilbert": "US",
	"chesapeake": "US",
	"irving": "US",
	"hialeah": "US",
	"garland": "US",
	"fremont": "US",
	"richmond": "US",
	"boise": "US",
	"baton rouge": "US",
	"des moines": "US",
	"salt lake city": "US",
	"slc": "US",
	"huntsville": "US",
	"mobile": "US",
	"little rock": "US",
	"fayetteville": "US",
	"hartford": "US",
	"new haven": "US",
	"stamford": "US",
	"wilmington": "US",
	"dover": "US",
	"tallahassee": "US",
	"fort lauderdale": "US",
	"gainesville": "US",
	"savannah": "US",
	"augusta": "US",
	"boise city": "US",
	"springfield": "US",
	"peoria": "US",
	"rockford": "US",
	"south bend": "US",
	"evansville": "US",
	"cedar rapids": "US",
	"topeka": "US",
	"lexington-fayette": "US",
	"shreveport": "US",
	"portland me": "US",
	"annapolis": "US",
	"worcester": "US",
	"grand rapids": "US",
	"ann arbor": "US",
	"lansing": "US",
	"flint": "US",
	"duluth": "US",
	"rochester": "US",
	"jackson": "US",
	"gulfport": "US",
	"st. joseph": "US",
	"saint joseph": "US",
	"billings": "US",
	"missoula": "US",
	"helena": "US",
	"concord": "US",
	"trenton": "US",
	"princeton": "US",
	"atlantic city": "US",
	"santa fe": "US",
	"las cruces": "US",
	"albany": "US",
	"syracuse": "US",
	"yonkers": "US",
	"asheville": "US",
	"fargo": "US",
	"bismarck": "US",
	"akron": "US",
	"dayton": "US",
	"canton": "US",
	"eugene": "US",
	"salem or": "US",
	"allentown": "US",
	"erie": "US",
	"harrisburg": "US",
	"scranton": "US",
	"providence": "US",
	"charleston": "US",
	"columbia": "US",
	"greenville": "US",
	"sioux falls": "US",
	"chattanooga": "US",
	"knoxville": "US",
	"el paso tx": "US",
	"amarillo": "US",
	"brownsville": "US",
	"corpus": "US",
	"mcallen": "US",
	"waco": "US",
	"burlington": "US",
	"montpelier": "US",
	"alexandria": "US",
	"lynchburg": "US",
	"roanoke": "US",
	"olympia": "US",
	"spokane": "US",
	"tacoma": "US",
	"morgantown": "US",
	"green bay": "US",
	"madison wi": "US",
	"cheyenne": "US",
	"casper": "US",
	"San Francisco": "US",
	"Marlborough": "US",
	"Berkshire County": "US",
	// USA (ADDITIONAL TOP METRO AREAS)
	"frisco": "US",
	"port st. lucie": "US",
	"santa clarita": "US",
	"montgomery": "US",
	"overland park": "US",
	"grand prairie": "US",
	"oxnard": "US",
	"fontana": "US",
	"modesto": "US",
	"moreno valley": "US",
	"huntington beach": "US",
	"glendale ca": "US",
	"glendale california": "US",
	"santa rosa": "US",
	"oceanside": "US",
	"rancho cucamonga": "US",
	"clarksville": "US",
	"murfreesboro": "US",
	"tempe": "US",
	"cape coral": "US",
	"pembroke pines": "US",
	"hollywood": "US",
	"miramar": "US",
	"coral springs": "US",
	"vancouver wa": "US",
	"vancouver washington": "US",
	"bellevue": "US",
	"kent": "US",
	"everett": "US",
	"pasadena tx": "US",
	"pasadena texas": "US",
	"pasadena ca": "US",
	"pasadena california": "US",
	"mckinney": "US",
	"kansas city ks": "US",
	"kansas city kansas": "US",
	"joliet": "US",
	"naperville": "US",
	"elgin": "US",
	"torrance": "US",
	"hayward": "US",
	"pomona": "US",
	"escondido": "US",
	"bridgeport": "US",
	"lakewood co": "US",
	"lakewood colorado": "US",
	"paterson": "US",
	"elizabeth": "US",
	"columbus ga": "US",
	"columbus georgia": "US",
	"macon": "US",
	"hampton": "US",
	"newport news": "US",
	"mesquite": "US",
	"denton": "US",
	"carrollton": "US",
	"beaumont": "US",
	"midland tx": "US",
	"midland texas": "US",
	"odessa": "US",
	"round rock": "US",
	"richardson": "US",
	"pearlyand": "US",
	"college station": "US",
	"tyler": "US",
	"wichita falls": "US",
	"lewisville": "US",
	"league city": "US",
	"allen": "US",
	"sugar land": "US",
	"edinburg": "US",
	"mission": "US",
	"longview": "US",
	"bryan": "US",
	"pharr": "US",
	"baytown": "US",
	"warren": "US",
	"sterling heights": "US",
	"dearborn": "US",
	"livonia": "US",
	"troy": "US",
	"westland": "US",
	"charleston sc": "US",
	"charleston south carolina": "US",
	"columbia sc": "US",
	"columbia south carolina": "US",
	"mount pleasant": "US",
	"rock hill": "US",
	"cranston": "US",
	"warwick": "US",
	"grand forks": "US",
	"columbia mo": "US",
	"columbia missouri": "US",
	"independence": "US",
	"lee's summit": "US",
	"st. charles": "US",
	"saint charles": "US",
	"provo": "US",
	"west valley city": "US",
	"west jordan": "US",
	"orem": "US",
	"sandy": "US",
	"ogden": "US",
	"st. george": "US",
	"saint george": "US",
	"el monte": "US",
	"fairfield ca": "US",
	"fairfield california": "US",
	"clearwater": "US",
	"rochester mn": "US",
	"rochester minnesota": "US",
	"carlsbad": "US",
	"westminster co": "US",
	"westminster colorado": "US",
	"downey": "US",
	"miami gardens": "US",
	"temecula": "US",
	"costa mesa": "US",
	"murrieta": "US",
	"ventura": "US",
	"pueblo": "US",
	"boulder": "US",
	"greeley": "US",
	"fort collins": "US",
	"longmont": "US",
	"arvada": "US",
	"west covina": "US",
	"broken arrow": "US",
	"norman": "US",
	"lawton": "US",
	"clovis": "US",
	"daly city": "US",
	"lakeland": "US",
	"deltona": "US",
	"daytona beach": "US",
	"palm bay": "US",
	"pompano beach": "US",
	"west palm beach": "US",
	"boca raton": "US",
	"deerfield beach": "US",
	"boynton beach": "US",
	"fort myers": "US",
	"bradenton": "US",
	"sarasota": "US",
	"pensacola": "US",
	"kissimmee": "US",
	"santa maria": "US",
	"norwalk ca": "US",
	"norwalk california": "US",
	"sandy springs": "US",
	"roswell ga": "US",
	"roswell georgia": "US",
	"alpharetta": "US",
	"marietta": "US",
	"hillsboro": "US",
	"gresham": "US",
	"beaverton": "US",
	"burbank": "US",
	"san mateo": "US",
	"el cajon": "US",
	"jurupa valley": "US",
	"rialto": "US",
	"antioch": "US",
	"south gate": "US",
	"vista": "US",
	"mission viejo": "US",
	"vacaville": "US",
	"carson": "US",
	"hesperia": "US",
	"redding": "US",
	"santa monica": "US",
	"chico": "US",
	"newton": "US",
	"somerville": "US",
	"lawrence ma": "US",
	"lawrence massachusetts": "US",
	"framingham": "US",
	"haverhill": "US",
	"waltham": "US",
	"malden": "US",
	"brookline": "US",
	"plymouth": "US",
	"woodbury": "US",
	"eagan": "US",
	"eden prairie": "US",
	"coon rapids": "US",
	"burnsville": "US",
	"blaine": "US",
	"lakeville": "US",
	"minnetonka": "US",
	"st. cloud": "US",
	"saint cloud": "US",
	"apple valley": "US",
	"edina": "US",
	"biloxi": "US",
	"hattiesburg": "US",
	"southaven": "US",
	"great falls": "US",
	"grand island": "US",
	"sparks": "US",
	"carson city": "US",
	"nashua": "US",
	"manchester nh": "US",
	"manchester new hampshire": "US",
	"clifton": "US",
	"cherry hill": "US",
	"middletown": "US",
	"union city": "US",
	"bayonne": "US",
	"vineland": "US",
	"rio rancho": "US",
	"rochester ny": "US",
	"rochester new york": "US",
	"schenectady": "US",
	"utica": "US",
	"white plains": "US",
	"troy ny": "US",
	"troy new york": "US",
	"niagara falls": "US",
	"wilmington nc": "US",
	"wilmington north carolina": "US",
	"high point": "US",
	"concord nc": "US",
	"concord north carolina": "US",
	"gastonia": "US",
	"jacksonville nc": "US",
	"jacksonville north carolina": "US",
	"rocky mount": "US",
	"chapel hill": "US",
	"burlington nc": "US",
	"burlington north carolina": "US",
	"canton oh": "US",
	"canton ohio": "US",
	"youngstown": "US",
	"springfield oh": "US",
	"springfield ohio": "US",
	"hamilton oh": "US",
	"hamilton ohio": "US",
	"kettering": "US",
	"elyria": "US",
	"lakewood oh": "US",
	"lakewood ohio": "US",
	"cuyahoga falls": "US",
	"salem oregon": "US",
	"reading pa": "US",
	"reading pennsylvania": "US",
	"bethlehem": "US",
	"lancaster pa": "US",
	"lancaster pennsylvania": "US",
	"altoona": "US",
	"rapid city": "US",
	"kingsport": "US",
	"franklin tn": "US",
	"franklin tennessee": "US",
	"bloomington in": "US",
	"bloomington indiana": "US",
	"carmel": "US",
	"fishers": "US",
	"hammond": "US",
	"gary": "US",
	"lafayette in": "US",
	"lafayette indiana": "US",
	"muncie": "US",
	"terre haute": "US",
	"kokomo": "US",
	"davenport": "US",
	"sioux city": "US",
	"waterloo": "US",
	"iowa city": "US",
	"council bluffs": "US",
	"ames": "US",
	"dubuque": "US",
	"lawrence ks": "US",
	"lawrence kansas": "US",
	"shawnee": "US",
	"manhattan ks": "US",
	"manhattan kansas": "US",
	"salina": "US",
	"hutchinson": "US",
	"owensboro": "US",
	"bowling green": "US",
	"covington": "US",
	"lafayette la": "US",
	"lafayette louisiana": "US",
	"lake charles": "US",
	"kenner": "US",
	"monroe la": "US",
	"monroe louisiana": "US",
	"portland maine": "US",
	"bangor": "US",
	"lewiston": "US",
	"frederick": "US",
	"gaithersburg": "US",
	"rockville": "US",
	"bowie": "US",
	"hagerstown": "US",
	"springfield ma": "US",
	"springfield massachusetts": "US",
	"lowell": "US",
	"cambridge massachusetts": "US",
	"new bedford": "US",
	"massachusetts": "US",
	"brockton": "US",
	"quincy ma": "US",
	"quincy massachusetts": "US",
	"lynn": "US",
	"fall river": "US"
};
