export const CANADA = {
	"gta": "CA",
	"winnipeg": "CA",
	"quebec city": "CA",
	"quebec": "CA",
	"québec": "CA",
	"hamilton": "CA",
	"kitchener": "CA",
	"waterloo": "CA",
	"kw": "CA",
	"london ontario": "CA",
	"halifax": "CA",
	"st. catharines": "CA",
	"saint catharines": "CA",
	"niagara": "CA",
	"oshawa": "CA",
	"victoria": "CA",
	"windsor": "CA",
	"saskatoon": "CA",
	"regina": "CA",
	"sherbrooke": "CA",
	"st. john's": "CA",
	"saint john's": "CA",
	"st johns": "CA",
	"barrie": "CA",
	"kelowna": "CA",
	"abbotsford": "CA",
	"sudbury": "CA",
	"greater sudbury": "CA",
	"kingston": "CA",
	"saguenay": "CA",
	"trois-rivieres": "CA",
	"trois rivieres": "CA",
	"guelph": "CA",
	"moncton": "CA",
	"brantford": "CA",
	"saint john": "CA",
	"st. john": "CA",
	"thunder bay": "CA",
	"peterborough": "CA",
	"lethbridge": "CA",
	"nanaimo": "CA",
	"kamloops": "CA",
	"chilliwack": "CA",
	"belleville": "CA",
	"fredericton": "CA",
	"charlottetown": "CA",
	"whitehorse": "CA",
	"yellowknife": "CA",
	"iqaluit": "CA",
	"mississauga": "CA",
	"brampton": "CA",
	"surrey": "CA",
	"laval": "CA",
	"vaughan": "CA",
	"gatineau": "CA",
	"longueuil": "CA",
	"burnaby": "CA",
	"markham": "CA",
	"richmond hill": "CA",
	"richmond bc": "CA",
	"oakville": "CA",
	"burlington": "CA",
	"coquitlam": "CA",
	"osoyoos": "CA",
	"leamington": "CA",
	"fort mcmurray": "CA",
	"grande prairie": "CA",
	"red deer": "CA",
	"medicine hat": "CA",
	"airdrie": "CA",
	"st. albert": "CA",
	"saint albert": "CA",
	"prince george": "CA",
	"vernon": "CA",
	"penticton": "CA",
	"campbell river": "CA",
	"brandon": "CA",
	"steinbach": "CA",
	"dieppe": "CA",
	"miramichi": "CA",
	"truro": "CA",
	"new glasgow": "CA",
	"sydney ns": "CA",
	"cape breton": "CA",
	"cambridge ontario": "CA",
	"whitby": "CA",
	"ajax": "CA",
	"milton": "CA",
	"clarington": "CA",
	"pickering": "CA",
	"niagara falls": "CA",
	"welland": "CA",
	"sarnia": "CA",
	"sault ste. marie": "CA",
	"sault ste marie": "CA",
	"north bay": "CA",
	"cornwall": "CA",
	"chatham-kent": "CA",
	"chatham kent": "CA",
	"st. thomas": "CA",
	"woodstock": "CA",
	"stratford": "CA",
	"orillia": "CA",
	"owen sound": "CA",
	"timmins": "CA",
	"levis": "CA",
	"granby": "CA",
	"saint-hyacinthe": "CA",
	"shawinigan": "CA",
	"drummondville": "CA",
	"joliette": "CA",
	"victoriaville": "CA",
	"rouyn-noranda": "CA",
	"moose jaw": "CA",
	"prince albert": "CA",
	"swift current": "CA"
};
