export const MALAWI = {
	"Malawi": "MW",
	"Lilongwe": "MW",
	"Blantyre": "MW",
	"Mzuzu": "MW",
	"Zomba": "MW",
	"Kasungu": "MW",
	"Mangochi": "MW",
	"Karonga": "MW",
	"Salima": "MW",
	"Nkhotakota": "MW",
	"Liwonde": "MW",
	"Nsanje": "MW",
	"Rumphi": "MW",
	"Mzimba": "MW",
	"Dedza": "MW",
	"Ncheu": "MW",
	"Luchenza": "MW",
	"Mchinji": "MW",
	"Dowa": "MW",
	"Ntchisi": "MW",
	"Chitipa": "MW",
	"Mulanje": "MW",
	"Thyolo": "MW",
	"Chikwawa": "MW",
	"Mwanza": "MW",
	"Balaka": "MW",
	"Machinga": "MW",
	"Phalombe": "MW",
	"Neno": "MW",
	"Likoma": "MW",
	"Monkey Bay": "MW",
	"Nkhata Bay": "MW",
	"Chintheche": "MW",
	"Livingstonia": "MW",
	"Ngabu": "MW",
	"Chipoka": "MW",
	"Namwera": "MW",
	"Ekwendeni": "MW",
	"Mikolongwe": "MW",
	"Nchalo": "MW"
};
