export const MOROCCO = {
	"Morocco": "MA",
	"Casablanca": "MA",
	"Rabat": "MA",
	"Marrakesh": "MA",
	"Fes": "MA",
	"Tangier": "MA",
	"Agadir": "MA",
	"Meknes": "MA",
	"Oujda": "MA",
	"Kenitra": "MA",
	"Tetouan": "MA",
	"Safi": "MA",
	"Temara": "MA",
	"Inezgane": "MA",
	"Mohammedia": "MA",
	"Laayoune": "MA",
	"Khouribga": "MA",
	"Beni Mellal": "MA",
	"Jorf El Melha": "MA",
	"Nador": "MA",
	"Taza": "MA",
	"Settat": "MA",
	"Berrechid": "MA",
	"Khemisset": "MA",
	"Guelmim": "MA",
	"Larache": "MA",
	"Ksar El Kebir": "MA",
	"Berkane": "MA",
	"Sidi Slimane": "MA",
	"Sidi Kacem": "MA",
	"Taroudant": "MA",
	"Essaouira": "MA",
	"Tiznit": "MA",
	"Ouarzazate": "MA",
	"Al Hoceima": "MA",
	"Taourirt": "MA",
	"Youssoufia": "MA",
	"Chefchaouen": "MA",
	"Dakhla": "MA",
	"Errachidia": "MA",
	"Midelt": "MA",
	"Azrou": "MA",
	"Ifrane": "MA",
	"Asilah": "MA",
	"Khenifra": "MA",
	"Sefrou": "MA",
	"Souk El Arbaa": "MA",
	"Oued Zem": "MA",
	"Kalaat Sraghna": "MA",
	"Benguerir": "MA",
	"Tan-Tan": "MA",
	"Sidi Ifni": "MA",
	"Boujdour": "MA",
	"Smara": "MA",
	"Tarfaya": "MA",
	"Fnideq": "MA",
	"M'diq": "MA",
	"Martil": "MA",
	"Guercif": "MA",
	"Fquih Ben Salah": "MA",
	"Ouazzane": "MA",
	"El Jadida": "MA",
	"Sidi Bennour": "MA",
	"Azemmour": "MA",
	"Tinghir": "MA",
	"Zagora": "MA",
	"Ahfir": "MA",
	"Berkane-MA": "MA",
	"Bouznika": "MA",
	"Skhirat": "MA",
	"Sale": "MA",
	"El Aaiun-MA": "MA",
	"Imzouren": "MA",
	"Sidi Yahya El Gharb": "MA",
	"Sidi Taibi": "MA",
	"Had Soualem": "MA",
	"Bouskoura": "MA",
	"Dar Bouazza": "MA",
	"Tit Mellil": "MA",
	"Lahraouyine": "MA",
	"Ayn Harrouda": "MA",
	"Demnate": "MA",
	"Chichaoua": "MA",
	"Ait Melloul": "MA",
	"Dcheira El Jihadia": "MA",
	"Biougra": "MA",
	"Ait Ourir": "MA",
	"Amizmiz": "MA",
	"Tahannaout": "MA",
	"El Hajeb": "MA",
	"Moulay Driss Zerhoun": "MA",
	"M'rirt": "MA",
	"Boujniba": "MA",
	"Hattane": "MA",
	"Kasba Tadla": "MA",
	"Zoumi": "MA",
	"Rissani": "MA",
	"Erfoud": "MA",
	"Boudnib": "MA",
	"Jorf": "MA",
	"Goulmima": "MA",
	"Tinjdad": "MA",
	"Boumalne Dades": "MA",
	"Kelaat M'Gouna": "MA",
	"M'hamid El Ghizlane": "MA",
	"Akka": "MA",
	"Tata": "MA",
	"Foum Zguid": "MA",
	"Assa": "MA",
	"Es-Semara": "MA",
	"Lagouira": "MA",
	"Oualidia": "MA",
	"Sidi Smail": "MA",
	"Zemamra": "MA",
	"Youssoufia-MA": "MA",
	"Chemaia": "MA",
	"Ounagha": "MA",
	"Tamanar": "MA",
	"Ait Baha": "MA",
	"Taliouine": "MA",
	"Oulad Teima": "MA",
	"Afourer": "MA",
	"Azilal": "MA",
	"Zaouiat Cheikh": "MA",
	"El Ksiba": "MA",
	"Ouaouizeght": "MA",
	"Tounfite": "MA",
	"Boumia": "MA",
	"Itzer": "MA",
	"Imilchil": "MA",
	"Agourai": "MA",
	"Ain Taoujdate": "MA",
	"Sabaa Aiyoun": "MA",
	"Bhalil": "MA",
	"El Menzel": "MA",
	"Ribate El Kheir": "MA",
	"Imouzzer Kandar": "MA",
	"Ahermoumou": "MA",
	"Guigou": "MA",
	"Boulemane": "MA",
	"Missour": "MA",
	"Outat El Haj": "MA",
	"Mohemmedia-MA": "MA"
};
