export const NIGERIA = {
	"Lagos": "NG",
	"Kano": "NG",
	"Ibadan": "NG",
	"Kaduna": "NG",
	"Port Harcourt": "NG",
	"Benin City": "NG",
	"Maiduguri": "NG",
	"Zaria": "NG",
	"Aba": "NG",
	"Jos": "NG",
	"Ilorin": "NG",
	"Oyo": "NG",
	"Enugu": "NG",
	"Abeokuta": "NG",
	"Abuja": "NG",
	"Sokoto": "NG",
	"Onitsha": "NG",
	"Warri": "NG",
	"Oshogbo": "NG",
	"Okene": "NG",
	"Calabar": "NG",
	"Katsina": "NG",
	"Akure": "NG",
	"Ile-Ife": "NG",
	"Bauchi": "NG",
	"Iseyin": "NG",
	"Minna": "NG",
	"Makurdi": "NG",
	"Owerri": "NG",
	"Umuahia": "NG",
	"Asaba": "NG",
	"Yola": "NG",
	"Gombe": "NG",
	"Jalingo": "NG",
	"Uyo": "NG",
	"Awka": "NG",
	"Ado Ekiti": "NG",
	"Lokoja": "NG",
	"Dutse": "NG",
	"Damaturu": "NG",
	"Birnin Kebbi": "NG",
	"Gusau": "NG",
	"Lafia": "NG",
	"Abakaliki": "NG",
	"Yenagoa": "NG",
	"Ikeja": "NG",
	"Nnewi": "NG",
	"Sapele": "NG",
	"Ede": "NG",
	"Ilesa": "NG",
	"Owo": "NG",
	"Offa": "NG",
	"Ikire": "NG",
	"Ikorodu": "NG",
	"Ogbomosho": "NG",
	"Ondo": "NG",
	"Oyo-NG": "NG",
	"Saki": "NG",
	"Bida": "NG",
	"Kontagora": "NG",
	"Suleja": "NG",
	"Potiskum": "NG",
	"Gashua": "NG",
	"Nguru": "NG",
	"Mubi": "NG",
	"Jimeta": "NG",
	"Bama": "NG",
	"Biu": "NG",
	"Kazaure": "NG",
	"Gumel": "NG",
	"Hadejia": "NG",
	"Daura": "NG",
	"Funtua": "NG",
	"Biunin Kudu": "NG",
	"Azare": "NG",
	"Misau": "NG",
	"Wukari": "NG",
	"Bussa": "NG",
	"Kishi": "NG",
	"Igboho": "NG",
	"Okuku": "NG",
	"Ila Orangun": "NG",
	"Ikrun": "NG",
	"Inisa": "NG",
	"Ilobu": "NG",
	"Ijebu Ode": "NG",
	"Ijebu Igbo": "NG",
	"Ilaro": "NG",
	"Sagamu": "NG",
	"Ota": "NG",
	"Badagry": "NG",
	"Epe": "NG",
	"Okitipupa": "NG",
	"Ikare": "NG",
	"Owo-NG": "NG",
	"Idanre": "NG",
	"Uromi": "NG",
	"Auchi": "NG",
	"Ekpoma": "NG",
	"Sapele-NG": "NG",
	"Ughelli": "NG",
	"Agbor": "NG",
	"Kwale": "NG",
	"Ogwashi Uku": "NG",
	"Nsukka": "NG",
	"Oji River": "NG",
	"Nsukka-NG": "NG",
	"Abiriba": "NG",
	"Ohafia": "NG",
	"Arochukwu": "NG",
	"Afikpo": "NG",
	"Okigwe": "NG",
	"Orlu": "NG",
	"Oguta": "NG",
	"Mbaise": "NG",
	"Ikot Ekpene": "NG",
	"Oron": "NG",
	"Abak": "NG",
	"Ikom": "NG",
	"Ogoja": "NG",
	"Obudu": "NG",
	"Anka": "NG",
	"Kaura Namoda": "NG",
	"Talata Mafara": "NG",
	"Argungu": "NG",
	"Yauri": "NG",
	"Zuru": "NG",
	"Yaba": "NG",
	"Lekki": "NG",
	"Gwagwalada": "NG",
	"Kuje": "NG"
};
