export const UAE: Record<string, string> = {
	"UAE": "AE",
	"Emirates": "AE",
	"Al Imarat": "AE",
	"Dubai": "AE",
	"Abu Dhabi": "AE",
	"Sharjah": "AE",
	"Al Ain": "AE",
	"Ajman": "AE",
	"Ras Al Khaimah": "AE",
	"Fujairah": "AE",
	"Umm Al Quwain": "AE",
	"Khor Fakkan": "AE",
	"Kalba": "AE",
	"Jebel Ali": "AE",
	"Dibba Al-Fujairah": "AE",
	"Dibba Al-Hisn": "AE",
	"Al Dhaid": "AE",
	"Al Ruwais": "AE",
	"Ruwais": "AE",
	"Madinat Zayed": "AE",
	"Liwa Oasis": "AE",
	"Dhaid": "AE",
	"Ghayathi": "AE",
	"Al Mirfa": "AE",
	"Hatta": "AE",
	"Ar-Rams": "AE",
	"Al Jazirah Al Hamra": "AE",
	"Masafi": "AE",
	"Al Madam": "AE",
	"Al Bataeh": "AE",
	"Al Hamriyah": "AE",
	"Al Khan": "AE",
	"Al Layyah": "AE"
};
