export const ALIASES: Record<string, string> = {
	"brasil": "BR",
	"brazil": "BR",
	"viet nam": "VN",
	"vietnam": "VN",
	"nigeria": "NG",
	"venezuela": "VE",
	"belarus": "BY",
	"peru": "PE",
	"kyrgyzstan": "KG",
	"myanmar": "MM",
	"burma": "MM",
	"czechia": "CZ",
	"czech republic": "CZ",
	"ivory coast": "CI",
	"cote divoire": "CI",
	"moldova": "MD",
	"republic of moldova": "MD",
	"tanzania": "TZ",
	"syria": "SY",
	"trinidad": "TT",
	"trinidad and tobago": "TT",
	"hong kong": "HK",
	"macau": "MO",
	"macao": "MO",
	"palestina": "PS",
	"palestine": "PS",
	"west bank": "PS",
	"macedonia": "MK",
	"north macedonia": "MK",
	"swaziland": "SZ",
	"eswatini": "SZ",
	"cabo verde": "CV",
	"cape verde": "CV",
	"timor leste": "TL",
	"east timor": "TL",
	"brunei": "BN",
	"laos": "LA",
	"bolivia": "BO",
	"south korea": "KR",
	"north korea": "KP",
	"republic of korea": "KR",
	"korea": "KR",

	"uk": "GB",
	"england": "GB",
	"scotland": "GB",
	"wales": "GB",
	"great britain": "GB",
	"ger": "DE",
	"usa": "US",
	"uae": "AE",
	"rsa": "ZA",
	"turkiye": "TR",

	"kampala": "UG",
	"lagos": "NG",
	"abuja": "NG",
	"kigali": "RW",
	"nairobi": "KE",
	"mombasa": "KE",
	"dar es salaam": "TZ",
	"lusaka": "ZM",
	"harare": "ZW",
	"addis ababa": "ET",
	"addis": "ET",
	"accra": "GH",
	"dakar": "SN",
	"yaounde": "CM",
	"douala": "CM",
	"abidjan": "CI",
	"johannesburg": "ZA",
	"cape town": "ZA",
	"durban": "ZA",
	"pretoria": "ZA",
	"antananarivo": "MG",
	"fianarantsoa": "MG",
	"toamasina": "MG",
	"antsirabe": "MG",
	// Middle East
	"islamabad": "PK",
	"karachi": "PK",
	"lahore": "PK",
	"rawalpindi": "PK",
	"tehran": "IR",
	"baghdad": "IQ",
	"amman": "JO",
	"beirut": "LB",
	"damascus": "SY",
	"riyadh": "SA",
	"jeddah": "SA",
	"doha": "QA",
	"muscat": "OM",
	"manama": "BH",
	"kuwait city": "KW",
	"sanaa": "YE",

	"dhaka": "BD",
	"chittagong": "BD",
	"colombo": "LK",
	"kathmandu": "NP",
	"bangalore": "IN",
	"bengaluru": "IN",
	"mumbai": "IN",
	"delhi": "IN",
	"new delhi": "IN",
	"hyderabad": "IN",
	"chennai": "IN",
	"kolkata": "IN",
	"pune": "IN",
	"kochi": "IN",
	"jakarta": "ID",
	"surabaya": "ID",
	"bandung": "ID",
	"bali": "ID",
	"semarang": "ID",
	"manila": "PH",
	"ho chi minh": "VN",
	"ho chi minh city": "VN",
	"saigon": "VN",
	"hanoi": "VN",
	"bangkok": "TH",
	"kuala lumpur": "MY",
	"yangon": "MM",
	// East Asia
	"seoul": "KR",
	"busan": "KR",
	"beijing": "CN",
	"shanghai": "CN",
	"guangzhou": "CN",
	"shenzhen": "CN",
	"wuhan": "CN",
	"hangzhou": "CN",
	"suzhou": "CN",
	"chengdu": "CN",
	"tokyo": "JP",
	"osaka": "JP",
	"taipei": "TW",
	// CIS / Eastern Europe
	"kyiv": "UA",
	"kiev": "UA",
	"kharkiv": "UA",
	"odessa": "UA",
	"minsk": "BY",
	"moscow": "RU",
	"saint petersburg": "RU",
	"st petersburg": "RU",
	"novosibirsk": "RU",
	"nizhny novgorod": "RU",
	"tbilisi": "GE",
	"yerevan": "AM",
	"baku": "AZ",
	"tashkent": "UZ",
	"almaty": "KZ",
	"bishkek": "KG",
	"osh": "KG",
	"dushanbe": "TJ",
	"ashgabat": "TM",
	"kabul": "AF",
	// Europe
	"london": "GB",
	"manchester": "GB",
	"birmingham": "GB",
	"edinburgh": "GB",
	"leeds": "GB",
	"paris": "FR",
	"lyon": "FR",
	"marseille": "FR",
	"toulouse": "FR",
	"lille": "FR",
	"grenoble": "FR",
	"berlin": "DE",
	"munich": "DE",
	"hamburg": "DE",
	"frankfurt": "DE",
	"stuttgart": "DE",
	"hannover": "DE",
	"braunschweig": "DE",
	"regensburg": "DE",
	"madrid": "ES",
	"barcelona": "ES",
	"rome": "IT",
	"milan": "IT",
	"naples": "IT",
	"turin": "IT",
	"amsterdam": "NL",
	"rotterdam": "NL",
	"brussels": "BE",
	"zurich": "CH",
	"geneva": "CH",
	"vienna": "AT",
	"graz": "AT",
	"warsaw": "PL",
	"krakow": "PL",
	"prague": "CZ",
	"budapest": "HU",
	"bucharest": "RO",
	"sofia": "BG",
	"belgrade": "RS",
	"tirana": "AL",
	"pristina": "XK",
	"prishtina": "XK",
	"vilnius": "LT",
	"riga": "LV",
	"tallinn": "EE",
	"helsinki": "FI",
	"oslo": "NO",
	"stockholm": "SE",
	"copenhagen": "DK",
	"dublin": "IE",
	"lisbon": "PT",
	"porto": "PT",
	"setubal": "PT",
	"athens": "GR",
	// North Africa
	"casablanca": "MA",
	"rabat": "MA",
	"tunis": "TN",
	"algiers": "DZ",
	"cairo": "EG",
	"alexandria": "EG",
	// Americas
	"toronto": "CA",
	"montreal": "CA",
	"vancouver": "CA",
	"ottawa": "CA",
	"new york": "US",
	"new york city": "US",
	"nyc": "US",
	"los angeles": "US",
	"san francisco": "US",
	"chicago": "US",
	"houston": "US",
	"seattle": "US",
	"boston": "US",
	"austin": "US",
	"dallas": "US",
	"atlanta": "US",
	"denver": "US",
	"portland": "US",
	"miami": "US",
	"menlo park": "US",
	"palo alto": "US",
	"los gatos": "US",
	"bainbridge island": "US",
	"sacramento": "US",
	"sao paulo": "BR",
	"rio de janeiro": "BR",
	"belo horizonte": "BR",
	"porto alegre": "BR",
	"buenos aires": "AR",
	"bogota": "CO",
	"santiago": "CL",
	"lima": "PE",
	"caracas": "VE",
	"asuncion": "PY",
	"san lorenzo": "PY",
	"mexico city": "MX",
	"guadalajara": "MX",
	"monterrey": "MX",

	"sydney": "AU",
	"melbourne": "AU",
	"brisbane": "AU",
	"perth": "AU",
	"auckland": "NZ",

	"west bengal": "IN",
	"vasai": "IN",
	"nuh mewat": "IN",
	"haryana": "IN",

	"hcm": "VN",
	"bac ninh": "VN",
	"bac giang": "VN",
	"soc son": "VN",
	"dong anh": "VN",
	"hai phong": "VN",
	"thai nguyen": "VN",

	"tanjombato": "MG",
	"ivandry": "MG",
	"madagasikara": "MG",

	"kocaeli": "TR",
	"gebze": "TR",

	"mohammedia": "MA",
	"maroc": "MA",

	"benin republic": "BJ",
	"lefkosa": "CY",

	"pelhrimov": "CZ",

	"کرج": "IR",

	"eygpt": "EG",

	"hongkong": "CN",
	"hong kong sar": "CN",
	"hksar": "CN",

	"prim kr": "RU",
	"primorsky": "RU"
};
