export const CN = {
	AF: "Afghanistan",
	AL: "Albania",
	DZ: "Algeria",
	AO: "Angola",
	AR: "Argentina",
	AU: "Australia",
	AT: "Austria",
	BD: "Bangladesh",
	BE: "Belgium",
	BR: "Brazil",
	BG: "Bulgaria",
	MM: "Myanmar",
	KH: "Cambodia",
	CM: "Cameroon",
	CA: "Canada",
	LK: "Sri Lanka",
	CL: "Chile",
	CN: "China",
	CO: "Colombia",
	CR: "Costa Rica",
	HR: "Croatia",
	CU: "Cuba",
	CZ: "Czech Republic",
	DK: "Denmark",
	DO: "Dominican Rep.",
	EC: "Ecuador",
	EG: "Egypt",
	ET: "Ethiopia",
	FI: "Finland",
	FR: "France",
	DE: "Germany",
	GH: "Ghana",
	GR: "Greece",
	GT: "Guatemala",
	HT: "Haiti",
	HN: "Honduras",
	HU: "Hungary",
	IN: "India",
	ID: "Indonesia",
	IR: "Iran",
	IQ: "Iraq",
	IE: "Ireland",
	IL: "Israel",
	IT: "Italy",
	JM: "Jamaica",
	JP: "Japan",
	JO: "Jordan",
	KZ: "Kazakhstan",
	KE: "Kenya",
	KR: "South Korea",
	KW: "Kuwait",
	LA: "Laos",
	LV: "Latvia",
	LB: "Lebanon",
	LY: "Libya",
	LT: "Lithuania",
	MY: "Malaysia",
	MX: "Mexico",
	MA: "Morocco",
	NP: "Nepal",
	NL: "Netherlands",
	NZ: "New Zealand",
	NI: "Nicaragua",
	NE: "Niger",
	NG: "Nigeria",
	NO: "Norway",
	PK: "Pakistan",
	PA: "Panama",
	PE: "Peru",
	PH: "Philippines",
	PL: "Poland",
	PT: "Portugal",
	QA: "Qatar",
	RO: "Romania",
	RU: "Russia",
	RW: "Rwanda",
	SA: "Saudi Arabia",
	SN: "Senegal",
	SG: "Singapore",
	SK: "Slovakia",
	SI: "Slovenia",
	SO: "Somalia",
	ZA: "South Africa",
	ES: "Spain",
	SD: "Sudan",
	SE: "Sweden",
	CH: "Switzerland",
	SY: "Syria",
	TH: "Thailand",
	TR: "Turkey",
	UG: "Uganda",
	UA: "Ukraine",
	AE: "UAE",
	US: "United States",
	GB: "United Kingdom",
	UY: "Uruguay",
	VE: "Venezuela",
	VN: "Vietnam",
	YE: "Yemen",
	ZM: "Zambia",
	ZW: "Zimbabwe",
	EE: "Estonia",
	GE: "Georgia",
	IS: "Iceland",
	MN: "Mongolia",
	MD: "Moldova",
	ME: "Montenegro",
	MK: "N. Macedonia",
	MG: "Madagascar",
	TZ: "Tanzania",
	MU: "Mauritius",
	BO: "Bolivia",
	BA: "Bosnia",
	BW: "Botswana",
	BN: "Brunei",
	BI: "Burundi",
	CF: "C.A.R.",
	TD: "Chad",
	CG: "Congo",
	CD: "DR Congo",
	SV: "El Salvador",
	FJ: "Fiji",
	GA: "Gabon",
	GM: "Gambia",
	GN: "Guinea",
	GY: "Guyana",
	LR: "Liberia",
	ML: "Mali",
	MR: "Mauritania",
	MZ: "Mozambique",
	NA: "Namibia",
	SL: "Sierra Leone",
	SR: "Suriname",
	TJ: "Tajikistan",
	TG: "Togo",
	TN: "Tunisia",
	UZ: "Uzbekistan",
	CI: "Côte d'Ivoire"
};

export const countryCodesSet = new Set<string>([
	"AF",
	"AL",
	"DZ",
	"AO",
	"AR",
	"AU",
	"AT",
	"BD",
	"BE",
	"BR",
	"BG",
	"MM",
	"KH",
	"CM",
	"CA",
	"LK",
	"CL",
	"CN",
	"CO",
	"CR",
	"HR",
	"CU",
	"CZ",
	"DK",
	"DO",
	"EC",
	"EG",
	"ET",
	"FI",
	"FR",
	"DE",
	"GH",
	"GR",
	"GT",
	"HT",
	"HN",
	"HU",
	"IN",
	"ID",
	"IR",
	"IQ",
	"IE",
	"IL",
	"IT",
	"JM",
	"JP",
	"JO",
	"KZ",
	"KE",
	"KR",
	"KW",
	"LA",
	"LV",
	"LB",
	"LY",
	"LT",
	"MY",
	"MX",
	"MA",
	"NP",
	"NL",
	"NZ",
	"NI",
	"NE",
	"NG",
	"NO",
	"PK",
	"PA",
	"PE",
	"PH",
	"PL",
	"PT",
	"QA",
	"RO",
	"RU",
	"RW",
	"SA",
	"SN",
	"SG",
	"SK",
	"SI",
	"SO",
	"ZA",
	"ES",
	"SD",
	"SE",
	"CH",
	"SY",
	"TH",
	"TR",
	"UG",
	"UA",
	"AE",
	"US",
	"GB",
	"UY",
	"VE",
	"VN",
	"YE",
	"ZM",
	"ZW",
	"EE",
	"GE",
	"IS",
	"MN",
	"MD",
	"ME",
	"MK",
	"MG",
	"TZ",
	"MU",
	"BO",
	"BA",
	"BW",
	"BN",
	"BI",
	"CF",
	"TD",
	"CG",
	"CD",
	"SV",
	"FJ",
	"GA",
	"GM",
	"GN",
	"GY",
	"LR",
	"ML",
	"MR",
	"MZ",
	"NA",
	"SL",
	"SR",
	"TJ",
	"TG",
	"TN",
	"UZ",
	"CI"
]);

export const famousCountries = {
	"afghanistan": "AF",
	"afg": "AF",
	"albania": "AL",
	"alb": "AL",
	"algeria": "DZ",
	"dza": "DZ",
	"american samoa": "AS",
	"asm": "AS",
	"andorra": "AD",
	"and": "AD",
	"angola": "AO",
	"ago": "AO",
	"anguilla": "AI",
	"aia": "AI",
	"antarctica": "AQ",
	"ata": "AQ",
	"antigua and barbuda": "AG",
	"antigua": "AG",
	"barbuda": "AG",
	"atg": "AG",
	"argentina": "AR",
	"arg": "AR",
	"armenia": "AM",
	"arm": "AM",
	"aruba": "AW",
	"abw": "AW",
	"australia": "AU",
	"aus": "AU",
	"oz": "AU",
	"aussie": "AU",
	"austria": "AT",
	"aut": "AT",
	"azerbaijan": "AZ",
	"aze": "AZ",
	"bahamas": "BS",
	"bhs": "BS",
	"bahrain": "BH",
	"bhr": "BH",
	"bangladesh": "BD",
	"bgd": "BD",
	"barbados": "BB",
	"brb": "BB",
	"belarus": "BY",
	"blr": "BY",
	"belgium": "BE",
	"bel": "BE",
	"belize": "BZ",
	"blz": "BZ",
	"benin": "BJ",
	"ben": "BJ",
	"bermuda": "BM",
	"bmu": "BM",
	"bhutan": "BT",
	"btn": "BT",
	"bolivia": "BO",
	"bol": "BO",
	"bosnia and herzegovina": "BA",
	"bosnia": "BA",
	"herzegovina": "BA",
	"bih": "BA",
	"botswana": "BW",
	"bwa": "BW",
	"brazil": "BR",
	"bra": "BR",
	"brunei": "BN",
	"brn": "BN",
	"bulgaria": "BG",
	"bgr": "BG",
	"burkina faso": "BF",
	"bfa": "BF",
	"burundi": "BI",
	"bdi": "BI",
	"cabo verde": "CV",
	"cape verde": "CV",
	"cpv": "CV",
	"cambodia": "KH",
	"khm": "KH",
	"cameroon": "CM",
	"cmr": "CM",
	"canada": "CA",
	"can": "CA",
	"cayman islands": "KY",
	"cym": "KY",
	"central african republic": "CF",
	"car": "CF",
	"caf": "CF",
	"chad": "TD",
	"tcd": "TD",
	"chile": "CL",
	"chl": "CL",
	"china": "CN",
	"chn": "CN",
	"prc": "CN",
	"colombia": "CO",
	"col": "CO",
	"comoros": "KM",
	"com": "KM",
	"congo": "CG",
	"cog": "CG",
	"democratic republic of the congo": "CD",
	"drc": "CD",
	"cod": "CD",
	"cook islands": "CK",
	"cok": "CK",
	"costa rica": "CR",
	"cri": "CR",
	"cote d'ivoire": "CI",
	"ivory coast": "CI",
	"civ": "CI",
	"croatia": "HR",
	"hrv": "HR",
	"cuba": "CU",
	"cub": "CU",
	"curacao": "CW",
	"cuw": "CW",
	"cyprus": "CY",
	"cyp": "CY",
	"czechia": "CZ",
	"czech republic": "CZ",
	"cze": "CZ",
	"denmark": "DK",
	"dnk": "DK",
	"djibouti": "DJ",
	"dji": "DJ",
	"dominica": "DM",
	"dma": "DM",
	"dominican republic": "DO",
	"dom": "DO",
	"ecuador": "EC",
	"ecu": "EC",
	"egypt": "EG",
	"egy": "EG",
	"el salvador": "SV",
	"slv": "SV",
	"equatorial guinea": "GQ",
	"gnq": "GQ",
	"eritrea": "ER",
	"eri": "ER",
	"estonia": "EE",
	"est": "EE",
	"eswatini": "SZ",
	"swaziland": "SZ",
	"swz": "SZ",
	"ethiopia": "ET",
	"eth": "ET",
	"falkland islands": "FK",
	"flk": "FK",
	"faroe islands": "FO",
	"fro": "FO",
	"fiji": "FJ",
	"fji": "FJ",
	"finland": "FI",
	"fin": "FI",
	"france": "FR",
	"fra": "FR",
	"french guiana": "GF",
	"guf": "GF",
	"french polynesia": "PF",
	"pyf": "PF",
	"gabon": "GA",
	"gab": "GA",
	"gambia": "GM",
	"gmb": "GM",
	"georgia": "GE",
	"geo": "GE",
	"germany": "DE",
	"deu": "DE",
	"deutschland": "DE",
	"ghana": "GH",
	"gha": "GH",
	"gibraltar": "GI",
	"gib": "GI",
	"greece": "GR",
	"grc": "GR",
	"greenland": "GL",
	"grl": "GL",
	"grenada": "GD",
	"grd": "GD",
	"guadeloupe": "GP",
	"glp": "GP",
	"guam": "GU",
	"gum": "GU",
	"guatemala": "GT",
	"gtm": "GT",
	"guernsey": "GG",
	"ggy": "GG",
	"guinea": "GN",
	"gin": "GN",
	"guinea-bissau": "GW",
	"gnb": "GW",
	"guyana": "GY",
	"guy": "GY",
	"haiti": "HT",
	"hti": "HT",
	"honduras": "HN",
	"hnd": "HN",
	"hong kong": "HK",
	"hkg": "HK",
	"hungary": "HU",
	"hun": "HU",
	"iceland": "IS",
	"isl": "IS",
	"india": "IN",
	"ind": "IN",
	"indonesia": "ID",
	"idn": "ID",
	"iran": "IR",
	"irn": "IR",
	"iraq": "IQ",
	"irq": "IQ",
	"ireland": "IE",
	"irl": "IE",
	"eire": "IE",
	"isle of man": "IM",
	"imn": "IM",
	"israel": "IL",
	"isr": "IL",
	"italy": "IT",
	"ita": "IT",
	"jamaica": "JM",
	"jam": "JM",
	"japan": "JP",
	"jpn": "JP",
	"jersey": "JE",
	"jey": "JE",
	"jordan": "JO",
	"jor": "JO",
	"kazakhstan": "KZ",
	"kaz": "KZ",
	"kenya": "KE",
	"ken": "KE",
	"kiribati": "KI",
	"kir": "KI",
	"north korea": "KP",
	"prk": "KP",
	"south korea": "KR",
	"kor": "KR",
	"kuwait": "KW",
	"kwt": "KW",
	"kyrgyzstan": "KG",
	"kgz": "KG",
	"laos": "LA",
	"lao": "LA",
	"latvia": "LV",
	"lva": "LV",
	"lebanon": "LB",
	"lbn": "LB",
	"lesotho": "LS",
	"lso": "LS",
	"liberia": "LR",
	"lbr": "LR",
	"libya": "LY",
	"lby": "LY",
	"liechtenstein": "LI",
	"lie": "LI",
	"lithuania": "LT",
	"ltu": "LT",
	"luxembourg": "LU",
	"lux": "LU",
	"macao": "MO",
	"macau": "MO",
	"mac": "MO",
	"madagascar": "MG",
	"mdg": "MG",
	"tana": "MG",
	"malawi": "MW",
	"mwi": "MW",
	"malaysia": "MY",
	"mys": "MY",
	"maldives": "MV",
	"mdv": "MV",
	"mali": "ML",
	"mli": "ML",
	"malta": "MT",
	"mlt": "MT",
	"marshall islands": "MH",
	"mhl": "MH",
	"martinique": "MQ",
	"mtq": "MQ",
	"mauritania": "MR",
	"mrt": "MR",
	"mauritius": "MU",
	"mus": "MU",
	"mayotte": "YT",
	"myt": "YT",
	"mexico": "MX",
	"mex": "MX",
	"micronesia": "FM",
	"fsm": "FM",
	"moldova": "MD",
	"mda": "MD",
	"monaco": "MC",
	"mco": "MC",
	"mongolia": "MN",
	"mng": "MN",
	"montenegro": "ME",
	"mne": "ME",
	"montserrat": "MS",
	"msr": "MS",
	"morocco": "MA",
	"mar": "MA",
	"mozambique": "MZ",
	"moz": "MZ",
	"myanmar": "MM",
	"burma": "MM",
	"mmr": "MM",
	"namibia": "NA",
	"nam": "NA",
	"nauru": "NR",
	"nru": "NR",
	"nepal": "NP",
	"npl": "NP",
	"netherlands": "NL",
	"holland": "NL",
	"nld": "NL",
	"new caledonia": "NC",
	"ncl": "NC",
	"new zealand": "NZ",
	"nzl": "NZ",
	"kiwi": "NZ",
	"nicaragua": "NI",
	"nic": "NI",
	"niger": "NE",
	"ner": "NE",
	"nigeria": "NG",
	"nga": "NG",
	"niue": "NU",
	"niu": "NU",
	"north macedonia": "MK",
	"macedonia": "MK",
	"mkd": "MK",
	"northern mariana islands": "MP",
	"mnp": "MP",
	"norway": "NO",
	"nor": "NO",
	"oman": "OM",
	"omn": "OM",
	"pakistan": "PK",
	"pak": "PK",
	"palau": "PW",
	"plw": "PW",
	"palestine": "PS",
	"pse": "PS",
	"panama": "PA",
	"pan": "PA",
	"papua new guinea": "PG",
	"png": "PG",
	"paraguay": "PY",
	"pry": "PY",
	"peru": "PE",
	"per": "PE",
	"philippines": "PH",
	"phl": "PH",
	"pitcairn": "PN",
	"pcn": "PN",
	"poland": "PL",
	"pol": "PL",
	"portugal": "PT",
	"prt": "PT",
	"puerto rico": "PR",
	"pri": "PR",
	"qatar": "QA",
	"qat": "QA",
	"reunion": "RE",
	"reu": "RE",
	"romania": "RO",
	"rou": "RO",
	"russia": "RU",
	"russian federation": "RU",
	"rus": "RU",
	"rwanda": "RW",
	"rwa": "RW",
	"saint barthelemy": "BL",
	"st barts": "BL",
	"blm": "BL",
	"saint helena": "SH",
	"shn": "SH",
	"saint kitts and nevis": "KN",
	"kna": "KN",
	"saint lucia": "LC",
	"lca": "LC",
	"saint martin": "MF",
	"maf": "MF",
	"saint pierre and miquelon": "PM",
	"spm": "PM",
	"saint vincent and the grenadines": "VC",
	"vct": "VC",
	"samoa": "WS",
	"wsm": "WS",
	"san marino": "SM",
	"smr": "SM",
	"sao tome and principe": "ST",
	"stp": "ST",
	"saudi arabia": "SA",
	"sau": "SA",
	"senegal": "SN",
	"sen": "SN",
	"serbia": "RS",
	"srb": "RS",
	"seychelles": "SC",
	"syc": "SC",
	"sierra leone": "SL",
	"sle": "SL",
	"singapore": "SG",
	"sgp": "SG",
	"sint maarten": "SX",
	"sxm": "SX",
	"slovakia": "SK",
	"svk": "SK",
	"slovenia": "SI",
	"svn": "SI",
	"solomon islands": "SB",
	"slb": "SB",
	"somalia": "SO",
	"som": "SO",
	"south africa": "ZA",
	"zaf": "ZA",
	"south sudan": "SS",
	"ssd": "SS",
	"spain": "ES",
	"esp": "ES",
	"sri lanka": "LK",
	"lka": "LK",
	"sudan": "SD",
	"sdn": "SD",
	"suriname": "SR",
	"sur": "SR",
	"sweden": "SE",
	"swe": "SE",
	"switzerland": "CH",
	"che": "CH",
	"syria": "SY",
	"syr": "SY",
	"taiwan": "TW",
	"twn": "TW",
	"tajikistan": "TJ",
	"tjk": "TJ",
	"tanzania": "TZ",
	"tza": "TZ",
	"thailand": "TH",
	"tha": "TH",
	"timor-leste": "TL",
	"east timor": "TL",
	"tls": "TL",
	"togo": "TG",
	"tgo": "TG",
	"tokelau": "TK",
	"tkl": "TK",
	"tonga": "TO",
	"ton": "TO",
	"trinidad and tobago": "TT",
	"trinidad": "TT",
	"tobago": "TT",
	"tto": "TT",
	"tunisia": "TN",
	"tun": "TN",
	"turkey": "TR",
	"turkiye": "TR",
	"tur": "TR",
	"turkmenistan": "TM",
	"tkm": "TM",
	"turks and caicos islands": "TC",
	"tca": "TC",
	"tuvalu": "TV",
	"tuv": "TV",
	"uganda": "UG",
	"uga": "UG",
	"ukraine": "UA",
	"ukr": "UA",
	"united arab emirates": "AE",
	"uae": "AE",
	"are": "AE",
	"united kingdom": "GB",
	"uk": "GB",
	"great britain": "GB",
	"britain": "GB",
	"gbr": "GB",
	"united states": "US",
	"usa": "US",
	"us": "US",
	"america": "US",
	"uruguay": "UY",
	"ury": "UY",
	"uzbekistan": "UZ",
	"uzb": "UZ",
	"vanuatu": "VU",
	"vut": "VU",
	"vatican city": "VA",
	"holy see": "VA",
	"vat": "VA",
	"venezuela": "VE",
	"ven": "VE",
	"vietnam": "VN",
	"vnm": "VN",
	"british virgin islands": "VG",
	"vgb": "VG",
	"us virgin islands": "VI",
	"vir": "VI",
	"wallis and futuna": "WF",
	"wlf": "WF",
	"western sahara": "EH",
	"esh": "EH",
	"yemen": "YE",
	"yem": "YE",
	"zambia": "ZM",
	"zmb": "ZM",
	"zimbabwe": "ZW",
	"zwe": "ZW"
};
