import { flagToCodeMap } from "./flags";
import { USA } from "./america";
import { CANADA } from "./canada";
import { MADAGASCAR } from "./madagascar";
import { PORTUGAL } from "./portugal";
import { CHINA } from "./china";
import { SWEDEN } from "./sweden";
import { GERMANY } from "./Germany";
import { MALAWI } from "./malawi";
import { MOROCCO } from "./morocco";
import { NIGERIA } from "./nigera";

export const CDICT_EXTENDEED = {
	// INDIA
	"calcutta": "IN",
	"noida": "IN",
	"gurgaon": "IN",
	"gurugram": "IN",
	"chandigarh": "IN",
	"coimbatore": "IN",
	"kochi": "IN",
	"cochin": "IN",
	"bhubaneswar": "IN",
	"indore": "IN",
	"nagpur": "IN",
	"mysore": "IN",
	"mysuru": "IN",
	"trivandrum": "IN",
	"thiruvananthapuram": "IN",
	"visakhapatnam": "IN",
	"vizag": "IN",
	"lucknow": "IN",
	"surat": "IN",
	"vadodara": "IN",
	"baroda": "IN",
	"patna": "IN",
	"bhopal": "IN",
	"amritsar": "IN",
	"jalandhar": "IN",
	"ludhiana": "IN",
	"agra": "IN",
	"varanasi": "IN",
	"banaras": "IN",
	"allahabad": "IN",
	"prayagraj": "IN",
	"ranchi": "IN",
	"guwahati": "IN",
	"shillong": "IN",
	"imphal": "IN",
	"aizawl": "IN",
	"kohima": "IN",
	"itanagar": "IN",
	"dispur": "IN",
	"gangtok": "IN",
	"panaji": "IN",
	"goa": "IN",
	"mangalore": "IN",
	"mangaluru": "IN",
	"hubli": "IN",
	"dharwad": "IN",
	"belgaum": "IN",
	"belagavi": "IN",
	"tumkur": "IN",
	"shimoga": "IN",
	"gulbarga": "IN",
	"davangere": "IN",
	"madurai": "IN",
	"tiruchirappalli": "IN",
	"trichy": "IN",
	"tiruppur": "IN",
	"salem": "IN",
	"erode": "IN",
	"tirunelveli": "IN",
	"vellore": "IN",
	"pondicherry": "IN",
	"puducherry": "IN",
	"warangal": "IN",
	"vijayawada": "IN",
	"rajkot": "IN",
	"gandhinagar": "IN",
	"anand": "IN",
	"bikaner": "IN",
	"jodhpur": "IN",
	"udaipur": "IN",
	"kota": "IN",
	"ajmer": "IN",
	"dehradun": "IN",
	"haridwar": "IN",
	"rishikesh": "IN",
	"nainital": "IN",
	"meerut": "IN",
	"ghaziabad": "IN",
	"faridabad": "IN",
	"kanpur": "IN",
	"bareilly": "IN",
	"moradabad": "IN",
	"aligarh": "IN",
	"gorakhpur": "IN",
	"raipur": "IN",
	"bilaspur": "IN",
	"jabalpur": "IN",
	"gwalior": "IN",
	"ujjain": "IN",
	"nashik": "IN",
	"aurangabad": "IN",
	"solapur": "IN",
	"kolhapur": "IN",
	"thane": "IN",
	"navi mumbai": "IN",
	"mumbai": "IN",
	"bombay": "IN",

	// BRAZIL
	"belo horizonte": "BR",
	"porto alegre": "BR",
	"fortaleza": "BR",
	"recife": "BR",
	"salvador": "BR",
	"curitiba": "BR",
	"manaus": "BR",
	"florianópolis": "BR",
	"florianopolis": "BR",
	"campinas": "BR",
	"brasília": "BR",
	"brasilia": "BR",
	"goiânia": "BR",
	"goiania": "BR",
	"natal": "BR",
	"teresina": "BR",
	"campo grande": "BR",
	"são luís": "BR",
	"sao luis": "BR",
	"belém": "BR",
	"belem": "BR",
	"maceió": "BR",
	"maceio": "BR",
	"são josé dos campos": "BR",
	"sao jose dos campos": "BR",
	"ribeirão preto": "BR",
	"ribeirao preto": "BR",
	"uberlândia": "BR",
	"uberlandia": "BR",
	"sorocaba": "BR",
	"contagem": "BR",
	"aracaju": "BR",
	"feira de santana": "BR",
	"joinville": "BR",
	"londrina": "BR",
	"juiz de fora": "BR",
	"niterói": "BR",
	"niteroi": "BR",
	"são bernardo do campo": "BR",
	"santo andré": "BR",
	"são caetano do sul": "BR",
	"osasco": "BR",
	"diadema": "BR",
	"porto velho": "BR",
	"macapá": "BR",
	"boa vista": "BR",
	"palmas": "BR",
	"cuiabá": "BR",
	"cuiaba": "BR",
	"vitória": "BR",

	// AFRICA
	// South Africa
	"cape town": "ZA",
	"johannesburg": "ZA",
	"pretoria": "ZA",
	"durban": "ZA",
	"soweto": "ZA",
	"port elizabeth": "ZA",
	"gqeberha": "ZA",
	"east london": "ZA",
	"bloemfontein": "ZA",
	"pietermaritzburg": "ZA",
	"polokwane": "ZA",
	"nelspruit": "ZA",
	"mbombela": "ZA",
	"kimberley": "ZA",
	"rustenburg": "ZA",
	"george": "ZA",
	"stellenbosch": "ZA",

	// Nigeria
	"ibadan": "NG",
	"kano": "NG",
	"port harcourt": "NG",
	"enugu": "NG",
	"benin city": "NG",
	"kaduna": "NG",
	"jos": "NG",
	"ilorin": "NG",
	"owerri": "NG",
	"warri": "NG",
	"asaba": "NG",
	"uyo": "NG",
	"calabar": "NG",
	"maiduguri": "NG",
	"sokoto": "NG",
	"abeokuta": "NG",

	// Ghana
	"kumasi": "GH",
	"tamale": "GH",
	"sekondi-takoradi": "GH",
	"sekondi takoradi": "GH",
	"cape coast": "GH",
	"tema": "GH",
	"koforidua": "GH",
	"sunyani": "GH",
	"ho": "GH",

	// Kenya
	"mombasa": "KE",
	"kisumu": "KE",
	"nakuru": "KE",
	"eldoret": "KE",
	"thika": "KE",
	"malindi": "KE",
	"kitale": "KE",
	"garissa": "KE",

	// Ethiopia
	"dire dawa": "ET",
	"mekelle": "ET",
	"gondar": "ET",
	"hawassa": "ET",
	"bahir dar": "ET",
	"jimma": "ET",
	"adama": "ET",

	// Tanzania
	"mwanza": "TZ",
	"arusha": "TZ",
	"moshi": "TZ",
	"tanga": "TZ",
	"dodoma": "TZ",
	"zanzibar": "TZ",

	// Uganda
	"gulu": "UG",
	"mbarara": "UG",
	"jinja": "UG",
	"entebbe": "UG",

	// Rwanda
	"kigali": "RW",
	"butare": "RW",
	"huye": "RW",
	"musanze": "RW",
	"gisenyi": "RW",

	// Cameroon
	"blantyre": "MW",
	"douala": "CM",
	"yaoundé": "CM",
	"yaounde": "CM",
	"bamenda": "CM",
	"bafoussam": "CM",

	// Egypt
	"alexandria": "EG",
	"giza": "EG",
	"luxor": "EG",
	"aswan": "EG",
	"port said": "EG",
	"suez": "EG",
	"mansoura": "EG",
	"tanta": "EG",
	"ismailia": "EG",
	"sharm el sheikh": "EG",
	"hurghada": "EG",

	// Morocco
	"fez": "MA",
	"fès": "MA",
	"marrakech": "MA",
	"marrakesh": "MA",
	"tangier": "MA",
	"tanger": "MA",
	"agadir": "MA",
	"meknes": "MA",
	"meknès": "MA",
	"oujda": "MA",
	"kenitra": "MA",
	"tetouan": "MA",
	"tétouan": "MA",
	"safi": "MA",
	"el jadida": "MA",
	"beni mellal": "MA",

	// Algeria
	"oran": "DZ",
	"constantine": "DZ",
	"annaba": "DZ",
	"blida": "DZ",
	"batna": "DZ",
	"sétif": "DZ",
	"setif": "DZ",
	"sidi bel abbès": "DZ",
	"tlemcen": "DZ",

	// Tunisia
	"sfax": "TN",
	"sousse": "TN",
	"kairouan": "TN",
	"bizerte": "TN",
	"gabès": "TN",
	"ariana": "TN",

	// Libya
	"tripoli": "LY",
	"benghazi": "LY",
	"misrata": "LY",

	// Senegal
	"thiès": "SN",
	"thies": "SN",
	"saint-louis": "SN",
	"ziguinchor": "SN",

	// Ivory Coast
	"abidjan": "CI",
	"bouaké": "CI",
	"bouake": "CI",
	"yamoussoukro": "CI",
	"daloa": "CI",

	// Other Africa
	"lomé": "TG",
	"lome": "TG",
	"cotonou": "BJ",
	"porto-novo": "BJ",
	"ouagadougou": "BF",
	"bobo-dioulasso": "BF",
	"niamey": "NE",
	"bamako": "ML",
	"conakry": "GN",
	"freetown": "SL",
	"monrovia": "LR",
	"bissau": "GW",
	"banjul": "GM",
	"n'djamena": "TD",
	"ndjamena": "TD",
	"bangui": "CF",
	"libreville": "GA",
	"port-gentil": "GA",
	"malabo": "GQ",
	"brazzaville": "CG",
	"pointe-noire": "CG",
	"lubumbashi": "CD",
	"mbuji-mayi": "CD",
	"kisangani": "CD",
	"goma": "CD",
	"khartoum": "SD",
	"omdurman": "SD",
	"port sudan": "SD",
	"juba": "SS",
	"asmara": "ER",
	"djibouti": "DJ",
	"mogadishu": "SO",
	"hargeisa": "SO",
	"port louis": "MU",
	"beau bassin": "MU",
	"quatre bornes": "MU",
	"lilongwe": "MW",
	"lusaka": "ZM",
	"ndola": "ZM",
	"kitwe": "ZM",
	"harare": "ZW",
	"bulawayo": "ZW",
	"maputo": "MZ",
	"beira": "MZ",
	"nampula": "MZ",
	"windhoek": "NA",
	"walvis bay": "NA",
	"gaborone": "BW",
	"francistown": "BW",
	"maseru": "LS",
	"mbabane": "SZ",
	"manzini": "SZ",
	"moroni": "KM",
	"victoria": "SC",
	"são tomé": "ST",
	"sao tome": "ST",
	"praia": "CV",
	"mindelo": "CV",
	"luanda": "AO",
	"huambo": "AO",
	"lubango": "AO",

	// SOUTHEAST ASIA─
	"ho chi minh city": "VN",
	"da nang": "VN",
	"da nang city": "VN",
	"can tho": "VN",
	"hue": "VN",
	"nha trang": "VN",
	"vung tau": "VN",
	"hai phong": "VN",
	"haiphong": "VN",
	"bien hoa": "VN",
	"buon ma thuot": "VN",
	"pleiku": "VN",
	"quy nhon": "VN",
	"vinh": "VN",
	"thai nguyen": "VN",
	"nam dinh": "VN",

	// Indonesia
	"surabaya": "ID",
	"bandung": "ID",
	"medan": "ID",
	"yogyakarta": "ID",
	"makassar": "ID",
	"semarang": "ID",
	"palembang": "ID",
	"tangerang": "ID",
	"depok": "ID",
	"bekasi": "ID",
	"bogor": "ID",
	"padang": "ID",
	"pekanbaru": "ID",
	"banjarmasin": "ID",
	"balikpapan": "ID",
	"samarinda": "ID",
	"pontianak": "ID",
	"manado": "ID",
	"denpasar": "ID",
	"lombok": "ID",
	"ambon": "ID",
	"jayapura": "ID",
	"sorong": "ID",
	"mataram": "ID",
	"kupang": "ID",
	"ende": "ID",
	"solo": "ID",
	"surakarta": "ID",
	"malang": "ID",

	// Malaysia
	"penang": "MY",
	"johor bahru": "MY",
	"george town": "MY",
	"ipoh": "MY",
	"shah alam": "MY",
	"petaling jaya": "MY",
	"subang jaya": "MY",
	"putrajaya": "MY",
	"cyberjaya": "MY",
	"kota kinabalu": "MY",
	"kuching": "MY",
	"sandakan": "MY",
	"miri": "MY",
	"sibu": "MY",
	"alor setar": "MY",
	"seremban": "MY",
	"taiping": "MY",
	"klang": "MY",
	"malacca": "MY",
	"melaka": "MY",

	// Thailand
	"chiang mai": "TH",
	"phuket": "TH",
	"pattaya": "TH",
	"khon kaen": "TH",
	"chiang rai": "TH",
	"hat yai": "TH",
	"udon thani": "TH",
	"nakhon ratchasima": "TH",
	"korat": "TH",
	"ubon ratchathani": "TH",
	"nonthaburi": "TH",
	"pak kret": "TH",
	"samut prakan": "TH",
	"rayong": "TH",
	"hua hin": "TH",

	// Philippines
	"cebu city": "PH",
	"davao": "PH",
	"davao city": "PH",
	"quezon city": "PH",
	"zamboanga": "PH",
	"general santos": "PH",
	"cagayan de oro": "PH",
	"iloilo": "PH",
	"bacolod": "PH",
	"caloocan": "PH",
	"taguig": "PH",
	"pasig": "PH",
	"makati": "PH",
	"marikina": "PH",
	"antipolo": "PH",
	"bacoor": "PH",
	"cavite": "PH",
	"baguio": "PH",
	"dagupan": "PH",
	"angeles": "PH",
	"olongapo": "PH",
	"tacloban": "PH",
	"legazpi": "PH",
	"naga": "PH",
	"butuan": "PH",
	"cotabato": "PH",
	"iligan": "PH",

	// Cambodia
	"phnom penh": "KH",
	"siem reap": "KH",
	"sihanoukville": "KH",
	"battambang": "KH",

	// Laos
	"vientiane": "LA",
	"luang prabang": "LA",
	"pakse": "LA",

	// Myanmar/Burma
	"mandalay": "MM",
	"naypyidaw": "MM",
	"yangon": "MM",
	"rangoon": "MM",
	"bago": "MM",
	"mawlamyine": "MM",
	"pathein": "MM",
	"taunggyi": "MM",

	// Sri Lanka
	"kandy": "LK",
	"galle": "LK",
	"jaffna": "LK",
	"negombo": "LK",
	"trincomalee": "LK",
	"batticaloa": "LK",
	"anuradhapura": "LK",
	"ratnapura": "LK",

	// Bangladesh
	"chittagong": "BD",
	"sylhet": "BD",
	"rajshahi": "BD",
	"khulna": "BD",
	"comilla": "BD",
	"mymensingh": "BD",
	"narayanganj": "BD",
	"gazipur": "BD",
	"rangpur": "BD",
	"barisal": "BD",

	// Nepal
	"pokhara": "NP",
	"lalitpur": "NP",
	"patan": "NP",
	"bhaktapur": "NP",
	"biratnagar": "NP",
	"birgunj": "NP",
	"bharatpur": "NP",
	"dharan": "NP",
	"butwal": "NP",

	// Singapore
	"jurong": "SG",
	"tampines": "SG",
	"woodlands": "SG",
	"ang mo kio": "SG",
	"bedok": "SG",
	"punggol": "SG",
	"sengkang": "SG",
	"toa payoh": "SG",

	// Brunei
	"bandar seri begawan": "BN",
	"bsb Brunei": "BN",
	"seria": "BN",
	"kuala belait": "BN",

	// Timor-Leste
	"dili": "TL",

	// MIDDLE EAST
	// UAE
	"sharjah": "AE",
	"ajman": "AE",
	"ras al khaimah": "AE",
	"fujairah": "AE",
	"al ain": "AE",
	"umm al quwain": "AE",

	// Saudi Arabia
	"mecca": "SA",
	"makkah": "SA",
	"medina": "SA",
	"madinah": "SA",
	"dammam": "SA",
	"khobar": "SA",
	"al khobar": "SA",
	"dhahran": "SA",
	"jubail": "SA",
	"yanbu": "SA",
	"taif": "SA",
	"tabuk": "SA",
	"abha": "SA",

	// Qatar
	"doha": "QA",
	"al wakrah": "QA",
	"al khor": "QA",
	"lusail": "QA",

	// Kuwait
	"kuwait city": "KW",
	"al ahmadi": "KW",
	"al jahra": "KW",
	"salmiya": "KW",

	// Oman
	"muscat": "OM",
	"salalah": "OM",
	"sohar": "OM",
	"nizwa": "OM",
	"sur": "OM",

	// Bahrain
	"manama": "BH",
	"riffa": "BH",
	"muharraq": "BH",
	"hamad town": "BH",

	// Jordan
	"zarqa": "JO",
	"irbid": "JO",
	"aqaba": "JO",
	// Lebanon
	"tripoli, lebanon": "LB",
	"sidon": "LB",
	"saida": "LB",
	"tyre": "LB",
	"jounieh": "LB",

	// Syria
	"aleppo": "SY",
	"damascus": "SY",
	"homs": "SY",
	"latakia": "SY",
	"hama": "SY",
	"deir ez-zor": "SY",

	// Iraq
	"basra": "IQ",
	"mosul": "IQ",
	"erbil": "IQ",
	"irbil": "IQ",
	"kirkuk": "IQ",
	"sulaymaniyah": "IQ",
	"najaf": "IQ",
	"karbala": "IQ",
	"nasiriyah": "IQ",
	"hillah": "IQ",

	// Iran
	"mashhad": "IR",
	"isfahan": "IR",
	"esfahan": "IR",
	"tabriz": "IR",
	"shiraz": "IR",
	"ahvaz": "IR",
	"qom": "IR",
	"karaj": "IR",
	"rasht": "IR",
	"kermanshah": "IR",
	"zahedan": "IR",
	"hamadan": "IR",
	"arak": "IR",
	"yazd": "IR",
	"qazvin": "IR",
	"ardabil": "IR",
	"gorgan": "IR",
	"urmia": "IR",
	"orumiyeh": "IR",
	"sanandaj": "IR",
	"birjand": "IR",
	"bushehr": "IR",
	"bandar abbas": "IR",
	"kish island": "IR",
	"kish": "IR",

	// Israel / Palestine
	"haifa": "IL",
	"beer sheva": "IL",
	"be'er sheva": "IL",
	"netanya": "IL",
	"herzliya": "IL",
	"ramat gan": "IL",
	"petah tikva": "IL",
	"rishon lezion": "IL",
	"ashdod": "IL",
	"ashkelon": "IL",
	"nazareth": "IL",
	"eilat": "IL",
	"rehovot": "IL",
	"holon": "IL",
	"bnei brak": "IL",
	"bat yam": "IL",

	// Turkey
	"izmir": "TR",
	"antalya": "TR",
	"bursa": "TR",
	"adana": "TR",
	"gaziantep": "TR",
	"konya": "TR",
	"kayseri": "TR",
	"mersin": "TR",
	"trabzon": "TR",
	"erzurum": "TR",
	"malatya": "TR",
	"eskişehir": "TR",
	"eskisehir": "TR",
	"samsun": "TR",
	"diyarbakır": "TR",
	"diyarbakir": "TR",
	"urfa": "TR",
	"şanlıurfa": "TR",
	"sanliurfa": "TR",
	"kahramanmaraş": "TR",
	"bodrum": "TR",
	"fethiye": "TR",

	// Armenia
	"gyumri": "AM",
	"vanadzor": "AM",

	// Azerbaijan
	"ganja": "AZ",
	"sumqayit": "AZ",
	"sumgait": "AZ",
	"nakhchivan": "AZ",

	// Georgia
	"kutaisi": "GE",
	"batumi": "GE",
	"rustavi": "GE",

	// CENTRAL ASIA─
	"almaty": "KZ",
	"astana": "KZ",
	"nur-sultan": "KZ",
	"shymkent": "KZ",
	"karaganda": "KZ",
	"aktobe": "KZ",
	"pavlodar": "KZ",
	"semey": "KZ",
	"taraz": "KZ",
	"oskemen": "KZ",
	"tashkent": "UZ",
	"samarkand": "UZ",
	"namangan": "UZ",
	"andijan": "UZ",
	"bukhara": "UZ",
	"fergana": "UZ",
	"nukus": "UZ",
	"bishkek": "KG",
	"osh": "KG",
	"dushanbe": "TJ",
	"khujand": "TJ",
	"ashgabat": "TM",
	"turkmenbashi": "TM",

	// Mongolia
	"ulaanbaatar": "MN",
	"erdenet": "MN",
	"darkhan": "MN",

	// EAST ASIA
	// China
	"xian": "CN",
	"xi'an": "CN",
	"wuhan": "CN",
	"tianjin": "CN",
	"nanjing": "CN",
	"nanking": "CN",
	"chongqing": "CN",
	"qingdao": "CN",
	"tsingtao": "CN",
	"wuxi": "CN",
	"suzhou": "CN",
	"zhengzhou": "CN",
	"dalian": "CN",
	"harbin": "CN",
	"kunming": "CN",
	"changsha": "CN",
	"fuzhou": "CN",
	"jinan": "CN",
	"hefei": "CN",
	"nanning": "CN",
	"taiyuan": "CN",
	"xiamen": "CN",
	"amoy": "CN",
	"wenzhou": "CN",
	"zhuhai": "CN",
	"foshan": "CN",
	"dongguan": "CN",
	"changchun": "CN",
	"shenyang": "CN",
	"zhongshan": "CN",
	"nanchang": "CN",
	"guiyang": "CN",
	"urumqi": "CN",
	"ürümqi": "CN",
	"lhasa": "CN",
	"lanzhou": "CN",
	"shijiazhuang": "CN",
	"haikou": "CN",
	"sanya": "CN",
	"zibo": "CN",
	"ningbo": "CN",
	"nantong": "CN",
	"huai'an": "CN",
	"liuzhou": "CN",
	"linyi": "CN",
	"quanzhou": "CN",
	"xuzhou": "CN",
	"yantai": "CN",
	"changzhou": "CN",
	"yangzhou": "CN",
	"heze": "CN",
	"baotou": "CN",
	"hohhot": "CN",
	"huhhot": "CN",
	"datong": "CN",
	"guilin": "CN",
	"zhangjiajie": "CN",
	"lijiang": "CN",
	"dali": "CN",
	"chengde": "CN",
	"tangshan": "CN",
	"baoding": "CN",
	"weifang": "CN",
	"jining": "CN",
	"tai'an": "CN",
	"zhenjiang": "CN",
	"taizhou": "CN",
	"huzhou": "CN",
	"jiaxing": "CN",
	"shaoxing": "CN",
	"jinhua": "CN",

	// Japan
	"fukuoka": "JP",
	"kobe": "JP",
	"hiroshima": "JP",
	"sendai": "JP",
	"kitakyushu": "JP",
	"chiba": "JP",
	"sakai": "JP",
	"kawasaki": "JP",
	"saitama": "JP",
	"kumamoto": "JP",
	"okayama": "JP",
	"shizuoka": "JP",
	"matsuyama": "JP",
	"niigata": "JP",
	"hamamatsu": "JP",
	"kagoshima": "JP",
	"naha": "JP",
	"okinawa": "JP",
	"kanazawa": "JP",
	"tsukuba": "JP",
	"kawagoe": "JP",
	"hakodate": "JP",
	"asahikawa": "JP",
	"matsumoto": "JP",
	"nagano": "JP",
	"nara": "JP",
	"wakayama": "JP",
	"toyama": "JP",
	"fukushima": "JP",
	"mito": "JP",
	"utsunomiya": "JP",
	"maebashi": "JP",

	// South Korea
	"busan": "KR",
	"pusan": "KR",
	"incheon": "KR",
	"daegu": "KR",
	"daejeon": "KR",
	"gwangju": "KR",
	"suwon": "KR",
	"ulsan": "KR",
	"changwon": "KR",
	"seongnam": "KR",
	"goyang": "KR",
	"yongin": "KR",
	"bucheon": "KR",
	"jeju": "KR",
	"cheju": "KR",
	"jeonju": "KR",
	"cheonan": "KR",
	"ansan": "KR",
	"anyang": "KR",
	"pohang": "KR",
	"gimhae": "KR",
	"gumi": "KR",
	"iksan": "KR",
	"gangnam": "KR",

	// Taiwan
	"taipei": "TW",
	"kaohsiung": "TW",
	"taichung": "TW",
	"tainan": "TW",
	"hsinchu": "TW",
	"keelung": "TW",
	"taoyuan": "TW",
	"zhongli": "TW",
	"hualien": "TW",

	// EAST EUROPE / RUSSIA / CENTRAL EUROPE─
	"kharkiv": "UA",
	"odessa": "UA",
	"odesa": "UA",
	"lviv": "UA",
	"dnipro": "UA",
	"dnipropetrovsk": "UA",
	"zaporizhzhia": "UA",
	"zaporizhzhe": "UA",
	"kryvyi rih": "UA",
	"mykolaiv": "UA",
	"mariupol": "UA",
	"vinnytsia": "UA",
	"chernihiv": "UA",
	"cherkasy": "UA",
	"poltava": "UA",
	"sumy": "UA",
	"zhytomyr": "UA",
	"kherson": "UA",
	"khmelnytskyi": "UA",
	"ivano-frankivsk": "UA",
	"ternopil": "UA",
	"lutsk": "UA",
	"uzhhorod": "UA",

	// Russia
	"yerevan": "AM",
	"baku": "AZ",
	"novosibirsk": "RU",
	"yekaterinburg": "RU",
	"ekaterinburg": "RU",
	"kazan": "RU",
	"nizhny novgorod": "RU",
	"st petersburg": "RU",
	"spb": "RU",
	"krasnoyarsk": "RU",
	"perm": "RU",
	"voronezh": "RU",
	"saratov": "RU",
	"krasnodar": "RU",
	"tolyatti": "RU",
	"togliatti": "RU",
	"ulyanovsk": "RU",
	"izhevsk": "RU",
	"barnaul": "RU",
	"ufa": "RU",
	"vladivostok": "RU",
	"irkutsk": "RU",
	"omsk": "RU",
	"tyumen": "RU",
	"kemerovo": "RU",
	"murmansk": "RU",
	"arkhangelsk": "RU",
	"stavropol": "RU",
	"bryansk": "RU",
	"tula": "RU",
	"ryazan": "RU",
	"kaliningrad": "RU",
	"yaroslavl": "RU",
	"orenburg": "RU",
	"chelyabinsk": "RU",
	"rostov-on-don": "RU",
	"rostov on don": "RU",
	"volgograd": "RU",
	"astrakhan": "RU",
	"samara": "RU",
	"khabarovsk": "RU",
	"chita": "RU",
	"yakutsk": "RU",
	"abakan": "RU",
	"novokuznetsk": "RU",
	"tomsk": "RU",
	"kursk": "RU",
	"lipetsk": "RU",
	"kirov": "RU",
	"ivanovo": "RU",
	"vladimir": "RU",
	"kostroma": "RU",
	"smolensk": "RU",
	"pskov": "RU",
	"tver": "RU",

	// Belarus
	"minsk": "BY",
	"gomel": "BY",
	"vitebsk": "BY",
	"hrodna": "BY",
	"grodno": "BY",
	"brest, belarus": "BY",
	"mogilev": "BY",
	"bobruisk": "BY",

	// Poland
	"warsaw": "PL",
	"krakow": "PL",
	"kraków": "PL",
	"wroclaw": "PL",
	"wrocław": "PL",
	"poznan": "PL",
	"poznań": "PL",
	"gdansk": "PL",
	"gdańsk": "PL",
	"gdynia": "PL",
	"lodz": "PL",
	"łódź": "PL",
	"szczecin": "PL",
	"bydgoszcz": "PL",
	"lublin": "PL",
	"katowice": "PL",
	"białystok": "PL",
	"bialystok": "PL",
	"rzeszów": "PL",
	"rzeszow": "PL",
	"toruń": "PL",
	"torun": "PL",
	"kielce": "PL",
	"gliwice": "PL",
	"zabrze": "PL",
	"bytom": "PL",
	"sosnowiec": "PL",
	"rybnik": "PL",
	"radom": "PL",
	"olsztyn": "PL",
	"opole": "PL",

	// Czech Republic / Slovakia
	"brno": "CZ",
	"ostrava": "CZ",
	"plzen": "CZ",
	"plzeň": "CZ",
	"liberec": "CZ",
	"olomouc": "CZ",
	"hradec kralove": "CZ",
	"hradec králové": "CZ",
	"české budějovice": "CZ",
	"ceske budejovice": "CZ",
	"ústí nad labem": "CZ",
	"usti nad labem": "CZ",
	"kladno": "CZ",
	"pardubice": "CZ",
	"košice": "SK",
	"kosice": "SK",
	"prešov": "SK",
	"presov": "SK",
	"žilina": "SK",
	"zilina": "SK",
	"banská bystrica": "SK",
	"banska bystrica": "SK",
	"nitra": "SK",
	"trnava": "SK",

	// Hungary
	"debrecen": "HU",
	"pécs": "HU",
	"pecs": "HU",
	"miskolc": "HU",
	"győr": "HU",
	"gyor": "HU",
	"szeged": "HU",
	"nyíregyháza": "HU",
	"nyiregyhaza": "HU",
	"kecskemét": "HU",
	"kecskemet": "HU",
	"székesfehérvár": "HU",

	// Romania
	"bucharest": "RO",
	"cluj-napoca": "RO",
	"cluj napoca": "RO",
	"timisoara": "RO",
	"timișoara": "RO",
	"iasi": "RO",
	"iași": "RO",
	"craiova": "RO",
	"brasov": "RO",
	"brașov": "RO",
	"galati": "RO",
	"galați": "RO",
	"constanta": "RO",
	"constanța": "RO",
	"ploiesti": "RO",
	"ploiești": "RO",
	"oradea": "RO",
	"arad": "RO",
	"pitesti": "RO",
	"pitești": "RO",
	"sibiu": "RO",
	"bacau": "RO",
	"bacău": "RO",
	"targu mures": "RO",
	"târgu mureș": "RO",

	// Bulgaria
	"plovdiv": "BG",
	"varna": "BG",
	"burgas": "BG",
	"stara zagora": "BG",
	"ruse": "BG",
	"pleven": "BG",
	"sliven": "BG",
	"dobrich": "BG",

	// Serbia
	"belgrade": "RS",
	"novi sad": "RS",
	"niš": "RS",
	"nis": "RS",
	"kragujevac": "RS",
	"subotica": "RS",
	"čačak": "RS",
	"cacak": "RS",

	// Croatia
	"zagreb": "HR",
	"split": "HR",
	"rijeka": "HR",
	"osijek": "HR",
	"zadar": "HR",
	"pula": "HR",
	"dubrovnik": "HR",
	"varaždin": "HR",
	"varazdin": "HR",
	"slavonski brod": "HR",
	"šibenik": "HR",

	// Bosnia
	"sarajevo": "BA",
	"banja luka": "BA",
	"tuzla": "BA",
	"zenica": "BA",
	"mostar": "BA",
	"brčko": "BA",

	// Slovenia
	"ljubljana": "SI",
	"maribor": "SI",
	"celje": "SI",
	"kranj": "SI",
	"koper": "SI",

	// North Macedonia
	"skopje": "MK",
	"bitola": "MK",
	"kumanovo": "MK",
	"ohrid": "MK",
	"tetovo": "MK",

	// Albania
	"tirana": "AL",
	"durrës": "AL",
	"durres": "AL",
	"vlorë": "AL",
	"vlore": "AL",
	"shkodër": "AL",
	"shkoder": "AL",
	"elbasan": "AL",

	// Moldova
	"chisinau": "MD",
	"chișinău": "MD",
	"balti": "MD",
	"bălți": "MD",

	// Montenegro
	"podgorica": "ME",
	"nikšić": "ME",
	"niksic": "ME",
	"budva": "ME",
	"bar, montenegro": "ME",

	// Kosovo
	"pristina": "XK",
	"prishtina": "XK",
	"prizren": "XK",
	"ferizaj": "XK",

	// Baltic States
	"tartu": "EE",
	"narva": "EE",
	"pärnu": "EE",
	"parnu": "EE",
	"kaunas": "LT",
	"klaipėda": "LT",
	"klaipeda": "LT",
	"šiauliai": "LT",
	"siauliai": "LT",
	"panevėžys": "LT",
	"panevezys": "LT",
	"jelgava": "LV",
	"liepāja": "LV",
	"liepaja": "LV",
	"jūrmala": "LV",
	"jurmala": "LV",
	"daugavpils": "LV",
	"rēzekne": "LV",

	// Nordic countries
	"göteborg": "SE",
	"goteborg": "SE",
	"linköping": "SE",
	"linkoping": "SE",
	"örebro": "SE",
	"orebro": "SE",
	"västerås": "SE",
	"vasteras": "SE",
	"umeå": "SE",
	"umea": "SE",
	"helsingborg": "SE",
	"norrköping": "SE",
	"norrkoping": "SE",
	"jönköping": "SE",
	"jonkoping": "SE",
	"lund": "SE",
	"gävle": "SE",
	"gavle": "SE",
	"sundsvall": "SE",
	"borås": "SE",
	"boras": "SE",
	"trondheim": "NO",
	"stavanger": "NO",
	"tromsø": "NO",
	"tromso": "NO",
	"drammen": "NO",
	"fredrikstad": "NO",
	"kristiansand": "NO",
	"lillehammer": "NO",
	"bodø": "NO",
	"bodo": "NO",
	"aalborg": "DK",
	"ålborg": "DK",
	"aarhus": "DK",
	"odense": "DK",
	"esbjerg": "DK",
	"randers": "DK",
	"kolding": "DK",
	"horsens": "DK",
	"vejle": "DK",
	"roskilde": "DK",
	"helsingør": "DK",
	"helsingor": "DK",
	"tampere": "FI",
	"turku": "FI",
	"åbo": "FI",
	"abo": "FI",
	"oulu": "FI",
	"jyväskylä": "FI",
	"jyvaskyla": "FI",
	"lahti": "FI",
	"kuopio": "FI",
	"espoo": "FI",
	"vantaa": "FI",
	"reykjavik": "IS",
	"akureyri": "IS",
	"torshavn": "FO",
	"tórshavn": "FO",
	"nuuk": "GL",
	"longyearbyen": "SJ",
	"longyearbyen, svalbard": "SJ",

	// Austria / Switzerland / Liechtenstein / Luxembourg
	"graz": "AT",
	"linz": "AT",
	"salzburg": "AT",
	"innsbruck": "AT",
	"klagenfurt": "AT",
	"villach": "AT",
	"wels": "AT",
	"st. pölten": "AT",
	"bern": "CH",
	"lausanne": "CH",
	"basel": "CH",
	"lugano": "CH",
	"winterthur": "CH",
	"st. gallen": "CH",
	"st gallen": "CH",
	"luzern": "CH",
	"lucerne": "CH",
	"biel": "CH",
	"bienne": "CH",
	"thun": "CH",
	"köniz": "CH",
	"vaduz": "LI",
	"luxembourg city": "LU",
	"esch-sur-alzette": "LU",
	"esch sur alzette": "LU",

	// Belgium / Netherlands
	"antwerp": "BE",
	"antwerpen": "BE",
	"ghent": "BE",
	"gent": "BE",
	"bruges": "BE",
	"brugge": "BE",
	"liège": "BE",
	"liege": "BE",
	"charleroi": "BE",
	"namur": "BE",
	"leuven": "BE",
	"mechelen": "BE",
	"hasselt": "BE",
	"eindhoven": "NL",
	"utrecht": "NL",
	"tilburg": "NL",
	"groningen": "NL",
	"breda": "NL",
	"nijmegen": "NL",
	"enschede": "NL",
	"haarlem": "NL",
	"arnhem": "NL",
	"zaandam": "NL",
	"amersfoort": "NL",
	"apeldoorn": "NL",
	"zwolle": "NL",
	"zoetermeer": "NL",
	"leiden": "NL",
	"maastricht": "NL",
	"dordrecht": "NL",
	"delft": "NL",
	"deventer": "NL",
	"alkmaar": "NL",
	"venlo": "NL",

	// France (additional cities)
	"île-de-france": "FR",
	"ile-de-france": "FR",
	"greater paris": "FR",
	"rennes": "FR",
	"montpellier": "FR",
	"strasbourg": "FR",
	"grenoble": "FR",
	"lille": "FR",
	"dijon": "FR",
	"clermont-ferrand": "FR",
	"angers": "FR",
	"brest": "FR",
	"le havre": "FR",
	"reims": "FR",
	"aix-en-provence": "FR",
	"tours": "FR",
	"saint-étienne": "FR",
	"saint-etienne": "FR",
	"perpignan": "FR",
	"rouen": "FR",
	"caen": "FR",
	"dunkerque": "FR",
	"amiens": "FR",
	"metz": "FR",
	"besançon": "FR",
	"besancon": "FR",
	"orléans": "FR",
	"orleans": "FR",
	"mulhouse": "FR",
	"cannes": "FR",
	"antibes": "FR",
	"avignon": "FR",
	"nîmes": "FR",
	"nimes": "FR",
	"toulon": "FR",
	"pau": "FR",
	"bayonne": "FR",
	"poitiers": "FR",
	"limoges": "FR",
	"la rochelle": "FR",
	"chambéry": "FR",
	"chambery": "FR",
	"valence": "FR",
	"troyes": "FR",
	"lorient": "FR",
	"quimper": "FR",

	// Germany (additional cities)
	"bavaria": "DE",
	"munich area": "DE",
	"nuremberg": "DE",
	"nürnberg": "DE",
	"bonn": "DE",
	"mannheim": "DE",
	"karlsruhe": "DE",
	"augsburg": "DE",
	"wiesbaden": "DE",
	"kiel": "DE",
	"freiburg": "DE",
	"mainz": "DE",
	"essen": "DE",
	"dortmund": "DE",
	"bochum": "DE",
	"aachen": "DE",
	"bielefeld": "DE",
	"halle": "DE",
	"magdeburg": "DE",
	"chemnitz": "DE",
	"braunschweig": "DE",
	"brunswick": "DE",
	"krefeld": "DE",
	"mönchengladbach": "DE",
	"monchengladbach": "DE",
	"wuppertal": "DE",
	"münster": "DE",
	"munster": "DE",
	"oberhausen": "DE",
	"gelsenkirchen": "DE",
	"hagen": "DE",
	"erfurt": "DE",
	"jena": "DE",
	"lübeck": "DE",
	"lubeck": "DE",
	"rostock": "DE",
	"göttingen": "DE",
	"gottingen": "DE",
	"darmstadt": "DE",
	"heidelberg": "DE",
	"potsdam": "DE",
	"saarbrücken": "DE",
	"saarbrucken": "DE",
	"kassel": "DE",
	"osnabrück": "DE",
	"osnabruk": "DE",
	"fürth": "DE",
	"furth": "DE",
	"regensburg": "DE",
	"trier": "DE",
	"wolfsburg": "DE",
	"ingolstadt": "DE",
	"ulm": "DE",
	"heilbronn": "DE",
	"pforzheim": "DE",
	"reutlingen": "DE",

	// UK (additional cities)
	"greater london": "GB",
	"greater manchester": "GB",
	"west midlands": "GB",
	"west yorkshire": "GB",
	"south yorkshire": "GB",
	"nottingham": "GB",
	"coventry": "GB",
	"leicester": "GB",
	"brighton": "GB",
	"southampton": "GB",
	"portsmouth": "GB",
	"cardiff": "GB",
	"swansea": "GB",
	"aberdeen": "GB",
	"dundee": "GB",
	"inverness": "GB",
	"northern ireland": "GB",
	"derry": "GB",
	"newcastle upon tyne": "GB",
	"newcastle": "GB",
	"wolverhampton": "GB",
	"derby": "GB",
	"stoke-on-trent": "GB",
	"stoke on trent": "GB",
	"plymouth": "GB",
	"reading": "GB",
	"hull": "GB",
	"kingston upon hull": "GB",
	"sunderland": "GB",
	"middlesbrough": "GB",
	"huddersfield": "GB",
	"bradford": "GB",
	"bolton": "GB",
	"wigan": "GB",
	"warrington": "GB",
	"blackpool": "GB",
	"blackburn": "GB",
	"burnley": "GB",
	"chorley": "GB",
	"exeter": "GB",
	"gloucester": "GB",
	"worcester": "GB",
	"hereford": "GB",
	"ipswich": "GB",
	"norwich": "GB",
	"peterborough": "GB",
	"cambridge uk": "GB",
	"oxford uk": "GB",
	"luton": "GB",
	"st albans": "GB",
	"milton keynes": "GB",
	"northampton": "GB",
	"bedford": "GB",
	"colchester": "GB",
	"chelmsford": "GB",
	"basildon": "GB",
	"southend-on-sea": "GB",
	"guildford": "GB",
	"woking": "GB",
	"slough": "GB",
	"watford": "GB",
	"hertford": "GB",
	"maidstone": "GB",
	"tunbridge wells": "GB",
	"folkestone": "GB",
	"hastings": "GB",
	"eastbourne": "GB",
	"worthing": "GB",
	"crawley": "GB",
	"isle of man": "IM",
	"douglas, isle of man": "IM",
	"jersey": "JE",
	"guernsey": "GG",

	// Ireland
	"cork": "IE",
	"limerick": "IE",
	"galway": "IE",
	"waterford": "IE",
	"drogheda": "IE",
	"dundalk": "IE",
	"swords": "IE",
	"tralee": "IE",
	"clonmel": "IE",
	"kilkenny": "IE",
	"sligo": "IE",

	// Spain (additional cities)
	"bilbao": "ES",
	"zaragoza": "ES",
	"palma": "ES",
	"palma de mallorca": "ES",
	"las palmas": "ES",
	"las palmas de gran canaria": "ES",
	"santa cruz de tenerife": "ES",
	"alicante": "ES",
	"murcia": "ES",
	"Cordoue": "ES",
	"Cordova": "ES",
	"cordoba": "ES",
	"valladolid": "ES",
	"vigo": "ES",
	"gijón": "ES",
	"gijon": "ES",
	"vitoria": "ES",
	"vitoria-gasteiz": "ES",
	"la coruña": "ES",
	"a coruña": "ES",
	"a coruna": "ES",
	"granada": "ES",
	"oviedo": "ES",
	"badalona": "ES",
	"terrassa": "ES",
	"sabadell": "ES",
	"hospitalet": "ES",
	"l'hospitalet de llobregat": "ES",
	"jerez de la frontera": "ES",
	"almería": "ES",
	"almeria": "ES",
	"tarragona": "ES",
	"lleida": "ES",
	"pamplona": "ES",
	"donostia": "ES",
	"san sebastián": "ES",
	"logroño": "ES",
	"logrone": "ES",
	"santander": "ES",
	"burgos": "ES",
	"toledo": "ES",
	"salamanca": "ES",
	"marbella": "ES",
	"málaga": "ES",
	"malaga": "ES",
	"tenerife": "ES",
	"ibiza": "ES",
	"menorca": "ES",

	// Portugal (additional)
	"braga": "PT",
	"coimbra": "PT",
	"setubal": "PT",
	"setúbal": "PT",
	"funchal": "PT",
	"ponta delgada": "PT",
	"aveiro": "PT",
	"leiria": "PT",
	"viseu": "PT",
	"évora": "PT",
	"evora": "PT",
	"faro": "PT",
	"guimarães": "PT",
	"guimaraes": "PT",
	"amadora": "PT",
	"almada": "PT",
	"barreiro": "PT",
	"matosinhos": "PT",
	"vila nova de gaia": "PT",

	// Italy (additional cities)
	"bologna": "IT",
	"venice": "IT",
	"venezia": "IT",
	"verona": "IT",
	"trieste": "IT",
	"padua": "IT",
	"padova": "IT",
	"bari": "IT",
	"palermo": "IT",
	"catania": "IT",
	"reggio calabria": "IT",
	"messina": "IT",
	"foggia": "IT",
	"salerno": "IT",
	"pescara": "IT",
	"ancona": "IT",
	"cagliari": "IT",
	"perugia": "IT",
	"brescia": "IT",
	"bergamo": "IT",
	"pisa": "IT",
	"livorno": "IT",
	"leghorn": "IT",
	"ferrara": "IT",
	"modena": "IT",
	"parma": "IT",
	"reggio emilia": "IT",
	"ravenna": "IT",
	"rimini": "IT",
	"como": "IT",
	"monza": "IT",
	"varese": "IT",
	"vicenza": "IT",
	"trento": "IT",
	"bolzano": "IT",
	"genova": "IT",
	"genoa": "IT",
	"la spezia": "IT",
	"sassari": "IT",

	// Greece (additional)
	"thessaloniki": "GR",
	"salonika": "GR",
	"patras": "GR",
	"heraklion": "GR",
	"iraklio": "GR",
	"volos": "GR",
	"ioannina": "GR",
	"larissa": "GR",
	"chalkida": "GR",
	"kavala": "GR",
	"rhodes": "GR",
	"corfu": "GR",
	"crete": "GR",
	"mykonos": "GR",
	"santorini": "GR",

	// Cyprus
	"nicosia": "CY",
	"limassol": "CY",
	"larnaca": "CY",
	"paphos": "CY",
	"famagusta": "CY",

	// Malta
	"valletta": "MT",
	"birkirkara": "MT",
	"sliema": "MT",
	"msida": "MT",
	"mosta": "MT",

	// LATIN AMERICA (beyond Brazil)
	"medellín": "CO",
	"medellin": "CO",
	"cali": "CO",
	"barranquilla": "CO",
	"cartagena": "CO",
	"cúcuta": "CO",
	"cucuta": "CO",
	"bucaramanga": "CO",
	"pereira": "CO",
	"manizales": "CO",
	"ibagué": "CO",
	"ibague": "CO",
	"villavicencio": "CO",
	"santa marta": "CO",
	"neiva": "CO",
	"armenia": "CO",
	"pasto": "CO",
	"montería": "CO",
	"monteria": "CO",
	"sincelejo": "CO",
	"popayán": "CO",
	"popayan": "CO",
	"valledupar": "CO",
	"quito": "EC",
	"guayaquil": "EC",
	"cuenca": "EC",
	"manta": "EC",
	"ambato": "EC",
	"esmeraldas": "EC",
	"ibarra": "EC",
	"loja": "EC",
	"riobamba": "EC",
	"la paz": "BO",
	"cochabamba": "BO",
	"santa cruz": "BO",
	"oruro": "BO",
	"potosí": "BO",
	"potosi": "BO",
	"sucre": "BO",
	"tarija": "BO",
	"asunción": "PY",
	"asuncion": "PY",
	"ciudad del este": "PY",
	"encarnación": "PY",
	"encarnacion": "PY",
	"montevideo": "UY",
	"maldonado": "UY",
	"salto": "UY",
	"paysandú": "UY",
	"paysandu": "UY",
	"caracas": "VE",
	"maracaibo": "VE",
	"valencia, venezuela": "VE",
	"maracay": "VE",
	"barquisimeto": "VE",
	"maturín": "VE",
	"maturin": "VE",
	"cumaná": "VE",
	"cumana": "VE",
	"havana": "CU",
	"la habana": "CU",
	"santiago de cuba": "CU",
	"holguín": "CU",
	"holguin": "CU",
	"camagüey": "CU",
	"camaguey": "CU",
	"santo domingo": "DO",
	"santiago de los caballeros": "DO",
	"san pedro de macorís": "DO",
	"san pedro de macoris": "DO",
	"san juan": "PR",
	"bayamón": "PR",
	"bayamon": "PR",
	"ponce": "PR",
	"caguas": "PR",
	"carolina, pr": "PR",
	"panama city": "PA",
	"colón": "PA",
	"colon, panama": "PA",
	"san josé": "CR",
	"san jose costa rica": "CR",
	"alajuela": "CR",
	"liberia, costa rica": "CR",
	"cartago, costa rica": "CR",
	"tegucigalpa": "HN",
	"san pedro sula": "HN",
	"managua": "NI",
	"granada, nicaragua": "NI",
	"san salvador": "SV",
	"santa ana, el salvador": "SV",
	"guatemala city": "GT",
	"quetzaltenango": "GT",
	"xela": "GT",
	"port-au-prince": "HT",
	"cap-haïtien": "HT",
	"cap-haitien": "HT",
	"kingston": "JM",
	"montego bay": "JM",
	"bridgetown": "BB",
	"port of spain": "TT",
	"chaguanas": "TT",
	"nassau": "BS",
	"freeport, bahamas": "BS",
	"basseterre": "KN",
	"kingstown": "VC",
	"castries": "LC",
	"roseau": "DM",
	"saint george's": "GD",
	"saint johns": "AG",
	"oranjestad": "AW",
	"willemstad": "CW",
	"philipsburg": "SX",
	"paramaribo": "SR",
	"cayenne": "GF",
	"belize city": "BZ",
	"belmopan": "BZ",

	// Peru (additional)
	"arequipa": "PE",
	"trujillo": "PE",
	"cusco": "PE",
	"cuzco": "PE",
	"iquitos": "PE",
	"chiclayo": "PE",
	"piura": "PE",
	"huancayo": "PE",
	"tacna": "PE",
	"ica": "PE",
	"pucallpa": "PE",

	// Chile (additional)
	"valparaíso": "CL",
	"valparaiso": "CL",
	"concepción": "CL",
	"concepcion": "CL",
	"la serena": "CL",
	"antofagasta": "CL",
	"temuco": "CL",
	"viña del mar": "CL",
	"vina del mar": "CL",
	"rancagua": "CL",
	"talca": "CL",
	"iquique": "CL",
	"arica": "CL",
	"coquimbo": "CL",
	"osorno": "CL",
	"puerto montt": "CL",

	// Argentina (additional)
	"córdoba": "AR",
	"cordoba, argentina": "AR",
	"rosario": "AR",
	"la plata": "AR",
	"mar del plata": "AR",
	"mendoza": "AR",
	"san miguel de tucumán": "AR",
	"tucumán": "AR",
	"tucuman": "AR",
	"salta": "AR",
	"santa fe, argentina": "AR",
	"corrientes": "AR",
	"misiones": "AR",
	"posadas": "AR",
	"neuquén": "AR",
	"neuquen": "AR",
	"bariloche": "AR",
	"san carlos de bariloche": "AR",
	"resistencia, argentina": "AR",
	"formosa": "AR",
	"san juan, argentina": "AR",
	"san luis, argentina": "AR",
	"catamarca": "AR",
	"jujuy": "AR",
	"la rioja, argentina": "AR",
	"río cuarto": "AR",
	"rio cuarto": "AR",

	// Mexico (additional)
	"puebla": "MX",
	"tijuana": "MX",
	"léon": "MX",
	"leon, mexico": "MX",
	"juárez": "MX",
	"ciudad juárez": "MX",
	"ciudad juarez": "MX",
	"torreón": "MX",
	"torreon": "MX",
	"san luis potosí": "MX",
	"san luis potosi": "MX",
	"mérida": "MX",
	"merida, mexico": "MX",
	"aguascalientes": "MX",
	"hermosillo": "MX",
	"saltillo": "MX",
	"mexicali": "MX",
	"culiacán": "MX",
	"culiacan": "MX",
	"acapulco": "MX",
	"morelia": "MX",
	"querétaro": "MX",
	"queretaro": "MX",
	"cancún": "MX",
	"cancun": "MX",
	"cuernavaca": "MX",
	"oaxaca": "MX",
	"veracruz": "MX",
	"chihuahua": "MX",
	"mazatlán": "MX",
	"mazatlan": "MX",
	"tepic": "MX",
	"colima": "MX",
	"tuxtla gutiérrez": "MX",
	"tuxtla gutierrez": "MX",
	"xalapa": "MX",
	"jalapa": "MX",
	"villahermosa": "MX",
	"cd. victoria": "MX",
	"ciudad victoria": "MX",
	"durango": "MX",
	"zacatecas": "MX",
	"guanajuato": "MX",
	"irapuato": "MX",
	"celaya": "MX",
	"ensenada": "MX",
	"la paz, mexico": "MX",
	"los cabos": "MX",

	// US (additional cities/regions)─
	"california": "US",
	"texas": "US",
	"florida": "US",
	"washington state": "US",
	"new york state": "US",
	"new york, ny": "US",
	"los angeles, ca": "US",
	"san francisco, ca": "US",
	"chicago, il": "US",
	"seattle, wa": "US",
	"boston, ma": "US",
	"austin, tx": "US",
	"denver, co": "US",
	"portland, or": "US",
	"atlanta, ga": "US",
	"miami, fl": "US",
	"philadelphia, pa": "US",
	"phoenix, az": "US",
	"minneapolis": "US",
	"st. louis": "US",
	"saint louis": "US",
	"detroit": "US",
	"pittsburgh": "US",
	"charlotte": "US",
	"raleigh": "US",
	"nashville": "US",
	"las vegas": "US",
	"salt lake city": "US",
	"indianapolis": "US",
	"columbus, oh": "US",
	"kansas city": "US",
	"baltimore": "US",
	"orlando": "US",
	"tucson": "US",
	"albuquerque": "US",
	"fresno": "US",
	"sacramento": "US",
	"long beach": "US",
	"mesa": "US",
	"omaha": "US",
	"cleveland": "US",
	"virginia beach": "US",
	"colorado springs": "US",
	"tampa": "US",
	"new orleans": "US",
	"arlington": "US",
	"wichita": "US",
	"bakersfield": "US",
	"aurora": "US",
	"anaheim": "US",
	"santa ana": "US",
	"corpus christi": "US",
	"riverside": "US",
	"san diego": "US",
	"lexington": "US",
	"st. paul": "US",
	"saint paul": "US",
	"anchorage": "US",
	"stockton": "US",
	"cincinnati": "US",
	"henderson": "US",
	"greensboro": "US",
	"jersey city": "US",
	"newark": "US",
	"buffalo": "US",
	"plano": "US",
	"lincoln": "US",
	"durham": "US",
	"madison": "US",
	"lubbock": "US",
	"garland": "US",
	"chandler": "US",
	"scottsdale": "US",
	"reno": "US",
	"norfolk": "US",
	"richmond": "US",
	"baton rouge": "US",
	"laredo": "US",
	"little rock": "US",
	"birmingham, al": "US",
	"jackson": "US",
	"spokane": "US",
	"des moines": "US",
	"rochester": "US",
	"tacoma": "US",
	"akron": "US",
	"shreveport": "US",
	"fort wayne": "US",
	"huntsville": "US",
	"grand rapids": "US",
	"salt lake": "US",
	"knoxville": "US",
	"memphis": "US",
	"tulsa": "US",
	"oklahoma city": "US",
	"el paso": "US",
	"fort worth": "US",
	"san antonio": "US",
	"hawaii": "US",
	"honolulu": "US",
	"maui": "US",
	"alaska": "US",
	"juneau": "US",
	"fairbanks": "US",
	"ohio": "US",
	"new jersey": "US",
	"north carolina": "US",
	"virginia": "US",
	"michigan": "US",
	"illinois": "US",
	"georgia, us": "US",
	"pennsylvania": "US",
	"massachusetts": "US",
	"arizona": "US",
	"indiana": "US",
	"tennessee": "US",
	"maryland": "US",
	"south carolina": "US",
	"connecticut": "US",
	"minnesota": "US",
	"wisconsin": "US",
	"louisiana": "US",
	"alabama": "US",
	"kentucky": "US",
	"oregon": "US",
	"iowa": "US",
	"utah": "US",
	"nevada": "US",
	"arkansas": "US",
	"kansas": "US",
	"mississippi": "US",
	"new mexico": "US",
	"nebraska": "US",
	"west virginia": "US",
	"idaho": "US",
	"new hampshire": "US",
	"maine": "US",
	"montana": "US",
	"rhode island": "US",
	"delaware": "US",
	"south dakota": "US",
	"north dakota": "US",
	"vermont": "US",
	"wyoming": "US",
	"remote, us": "US",
	"remote, usa": "US",

	// CANADA (additional)─
	"ontario": "CA",
	"british columbia": "CA",
	"quebec": "CA",
	"alberta": "CA",
	"nova scotia": "CA",
	"winnipeg": "CA",
	"hamilton, ontario": "CA",
	"london, ontario": "CA",
	"kitchener": "CA",
	"waterloo, canada": "CA",
	"guelph": "CA",
	"kingston, ontario": "CA",
	"sudbury": "CA",
	"thunder bay": "CA",
	"saskatoon": "CA",
	"regina": "CA",
	"lethbridge": "CA",
	"red deer": "CA",
	"victoria, bc": "CA",
	"kelowna": "CA",
	"burnaby": "CA",
	"surrey": "CA",
	"abbotsford": "CA",
	"langley": "CA",
	"richmond, bc": "CA",
	"coquitlam": "CA",
	"new brunswick": "CA",
	"moncton": "CA",
	"fredericton": "CA",
	"saint john, nb": "CA",
	"halifax": "CA",
	"charlottetown": "CA",
	"st. john's": "CA",
	"st johns newfoundland": "CA",
	"northwest territories": "CA",
	"nunavut": "CA",
	"yukon": "CA",
	"whitehorse": "CA",
	"iqaluit": "CA",
	"yellowknife": "CA",
	"gatineau": "CA",
	"laval": "CA",
	"longueuil": "CA",
	"sherbrooke": "CA",
	"saguenay": "CA",
	"trois-rivières": "CA",
	"trois-rivieres": "CA",
	"québec city": "CA",
	"quebec city": "CA",

	// AUSTRALIA (additional)
	"new south wales": "AU",
	"victoria vic": "AU",
	"queensland": "AU",
	"canberra": "AU",
	"hobart": "AU",
	"darwin": "AU",
	"gold coast": "AU",
	"newcastle, australia": "AU",
	"wollongong": "AU",
	"geelong": "AU",
	"ballarat": "AU",
	"bendigo": "AU",
	"albury": "AU",
	"townsville": "AU",
	"cairns": "AU",
	"rockhampton": "AU",
	"toowoomba": "AU",
	"sunshine coast": "AU",
	"mackay": "AU",
	"bundaberg": "AU",
	"launceston": "AU",
	"alice springs": "AU",
	"western australia": "AU",
	"south australia": "AU",
	"tasmania": "AU",
	"northern territory": "AU",
	"act": "AU",
	"fremantle": "AU",
	"mandurah": "AU",
	"bunbury": "AU",
	"geraldton": "AU",
	"kalgoorlie": "AU",

	// NEW ZEALAND (additional)
	"christchurch": "NZ",
	"hamilton, nz": "NZ",
	"hamilton, new zealand": "NZ",
	"tauranga": "NZ",
	"napier": "NZ",
	"palmerston north": "NZ",
	"dunedin": "NZ",
	"nelson": "NZ",
	"rotorua": "NZ",
	"invercargill": "NZ",
	"whangarei": "NZ",
	"gisborne": "NZ",
	"whanganui": "NZ",
	"new plymouth": "NZ",
	"queenstown": "NZ",

	// PACIFIC ISLANDS─
	"suva": "FJ",
	"nadi": "FJ",
	"lautoka": "FJ",
	"apia": "WS",
	"nuku'alofa": "TO",
	"nukualofa": "TO",
	"pago pago": "AS",
	"port moresby": "PG",
	"honiara": "SB",
	"port vila": "VU",
	"noumea": "NC",
	"nouméa": "NC",
	"papeete": "PF",
	"tahiti": "PF",
	"hagåtña": "GU",
	"hagatna": "GU",
	"guam": "GU",
	"saipan": "MP",
	"tarawa": "KI",
	"funafuti": "TV",
	"yaren": "NR",
	"palikir": "FM",
	"majuro": "MH",
	"ngerulmud": "PW",

	// COUNTRY NAME ALIASES
	"türkiye": "TR",
	"eire": "IE",
	"republic of ireland": "IE",
	"republic of south africa": "ZA",
	"taiwan": "TW",
	"republic of china": "TW",
	"r.o.c.": "TW",
	"hong kong sar": "HK",
	"hong kong s.a.r.": "HK",
	"macau": "MO",
	"macao": "MO",
	"kosovo": "XK",
	"republic of kosovo": "XK",
	"palestine": "PS",
	"west bank": "PS",
	"gaza": "PS",
	"north korea": "KP",
	"dprk": "KP",
	"myanmar/burma": "MM",
	"timor-leste": "TL",
	"east timor": "TL",
	"cabo verde": "CV",
	"eswatini": "SZ",
	"swaziland": "SZ",
	"republic of north macedonia": "MK",
	"byelorussia": "BY",
	"byelorussian": "BY",
	"czech rep": "CZ",
	"república dominicana": "DO",
	"slovak republic": "SK",
	"south sudan": "SS",
	"south soudan": "SS",
	"república de guinea ecuatorial": "GQ",
	"equatorial guinea": "GQ",
	"sao tome and principe": "ST",
	"são tomé and príncipe": "ST",
	"democratic republic of the congo": "CD",
	"drc": "CD",
	"republic of the congo": "CG",
	"central african rep": "CF",
	"car": "CF",
	"guinea-bissau": "GW",
	"republic of guinea-bissau": "GW",
	"comoros": "KM",
	"union of comoros": "KM",
	"seychelles": "SC",
	"republic of seychelles": "SC",
	"western sahara": "EH",
	"sahrawi": "EH",
	"eritrea": "ER",
	"republic of eritrea": "ER",
	"republic of djibouti": "DJ",
	"somaliland": "SO",
	"puntland": "SO",
	"surinam": "SR",
	"french guiana": "GF",
	"french guyana": "GF",
	"guadeloupe": "GP",
	"martinique": "MQ",
	"réunion": "RE",
	"reunion": "RE",
	"mayotte": "YT",
	"new caledonia": "NC",
	"french polynesia": "PF",
	"wallis and futuna": "WF",
	"saint martin": "MF",
	"saint barthélemy": "BL",
	"saint barthelemy": "BL",
	"saint pierre and miquelon": "PM",
	"american samoa": "AS",
	"northern mariana islands": "MP",
	"us virgin islands": "VI",
	"british virgin islands": "VG",
	"turks and caicos": "TC",
	"cayman islands": "KY",
	"bermuda": "BM",
	"montserrat": "MS",
	"anguilla": "AI",
	"antigua and barbuda": "AG",
	"saint kitts and nevis": "KN",
	"saint lucia": "LC",
	"saint vincent and the grenadines": "VC",
	"trinidad & tobago": "TT",
	"falkland islands": "FK",
	"malvinas": "FK",
	"south georgia": "GS",
	"british indian ocean territory": "IO",
	"diego garcia": "IO",
	"cocos islands": "CC",
	"christmas island": "CX",
	"norfolk island": "NF",
	"cook islands": "CK",
	"niue": "NU",
	"tokelau": "TK",
	"vanuatu": "VU",
	"tuvalu": "TV",
	"nauru": "NR",
	"kiribati": "KI",
	"marshall islands": "MH",
	"micronesia": "FM",
	"palau": "PW",
	"papua new guinea": "PG",
	"png": "PG",
	"solomon islands": "SB",
	"tonga": "TO",
	"samoa": "WS",
	"andorra": "AD",
	"andorra la vella": "AD",
	"san marino": "SM",
	"city of san marino": "SM",
	"monaco": "MC",
	"vatican": "VA",
	"holy see": "VA",
	"liechtenstein": "LI",
	"gibraltar": "GI",

	// DEVELOPER SHORTHAND─
	"yeg": "CA",
	"yvr": "CA",
	"yyz": "CA",
	"yow": "CA",
	"yul": "CA",
	"yyc": "CA",
	"pdx": "US",
	"chi": "US",
	"atl": "US",
	"phx": "US",
	"dfw": "US",
	"msp": "US",
	"ord": "US",
	"lax": "US",
	"nyc": "US",
	"sfo": "US",
	"sea": "US",
	"bos": "US",
	"iad": "US",
	"den": "US",
	"mia": "US",
	"syd": "AU",
	"mel": "AU",
	"bne": "AU",
	"per": "AU",
	"adl": "AU",
	"cbr": "AU",
	"jhb": "ZA",
	"cpt": "ZA",
	"dbn": "ZA",
	"lon": "GB",
	"lhr": "GB",
	"man": "GB",
	"bom": "IN",
	"del": "IN",
	"blr": "IN",
	"hyd": "IN",
	"maa": "IN",
	"ccu": "IN",
	"pnq": "IN",
	"ams": "NL",
	"ber": "DE",
	"muc": "DE",
	"fra": "DE",
	"ham": "DE",
	"cdg": "FR",
	"par": "FR",
	"mad": "ES",
	"bcn": "ES",
	"mxp": "IT",
	"mil": "IT",
	"fco": "IT",
	"gru": "BR",
	"gig": "BR",
	"bsb": "BR",
	"mex": "MX",
	"gua": "GT",
	"bog": "CO",
	"lim": "PE",
	"scl": "CL",
	"eze": "AR",
	"tyo": "JP",
	"nrt": "JP",
	"kix": "JP",
	"icn": "KR",
	"sel": "KR",
	"pek": "CN",
	"pvg": "CN",
	"szx": "CN",
	"sin": "SG",
	"kul": "MY",
	"bkk": "TH",
	"cgk": "ID",
	"mnl": "PH",
	"hkg": "HK",
	"tpe": "TW",
	"dxb": "AE",
	"auh": "AE",
	"doh": "QA",
	"ruh": "SA",
	"tlv": "IL",
	"ist": "TR",
	"mow": "RU",
	"svo": "RU",
	"led": "RU",
	"cai": "EG",
	"los": "NG",
	"nbo": "KE",
	"add": "ET",
	"acc": "GH",
	"cmn": "MA",
	"alg": "DZ",
	"jnb": "ZA",
	"vie": "AT",
	"zrh": "CH",
	"bru": "BE",
	"lis": "PT",
	"dub": "IE",
	"ath": "GR",
	"hel": "FI",
	"arn": "SE",
	"cph": "DK",
	"osl": "NO",
	"rix": "LV",
	"vno": "LT",
	"tll": "EE",
	"waw": "PL",
	"prg": "CZ",
	"bud": "HU",
	"otp": "RO",
	"sof": "BG",
	"beg": "RS",
	"zag": "HR",
	"lju": "SI",
	"bts": "SK",
	"kiv": "MD",
	"tbs": "GE",
	"evn": "AM",
	"gyd": "AZ",
	"ala": "KZ",
	"tas": "UZ",
	"fru": "KG",
	"dyu": "TJ",
	"asg": "TM",
	"uln": "MN",

	// Common "City, Country" combos developers write
	"london, uk": "GB",
	"london, england": "GB",
	"london, gb": "GB",
	"london, united kingdom": "GB",
	"paris, france": "FR",
	"berlin, germany": "DE",
	"berlin, deutschland": "DE",
	"amsterdam, netherlands": "NL",
	"amsterdam, nl": "NL",
	"madrid, spain": "ES",
	"rome, italy": "IT",
	"tokyo, japan": "JP",
	"beijing, china": "CN",
	"shanghai, china": "CN",
	"seoul, south korea": "KR",
	"seoul, korea": "KR",
	"singapore, sg": "SG",
	"sydney, australia": "AU",
	"toronto, canada": "CA",
	"montreal, canada": "CA",
	"moscow, russia": "RU",
	"dubai, uae": "AE",
	"dubai, united arab emirates": "AE",
	"nairobi, kenya": "KE",
	"lagos, nigeria": "NG",
	"cairo, egypt": "EG",
	"mumbai, india": "IN",
	"bangalore, india": "IN",
	"bangalore, karnataka": "IN",
	"delhi, india": "IN",
	"hyderabad, india": "IN",
	"pune, india": "IN",
	"chennai, india": "IN",
	"tehran, iran": "IR",
	"istanbul, turkey": "TR",
	"istanbul, türkiye": "TR",
	"athens, greece": "GR",
	"vienna, austria": "AT",
	"zurich, switzerland": "CH",
	"brussels, belgium": "BE",
	"lisbon, portugal": "PT",
	"dublin, ireland": "IE",
	"oslo, norway": "NO",
	"stockholm, sweden": "SE",
	"helsinki, finland": "FI",
	"warsaw, poland": "PL",
	"prague, czech republic": "CZ",
	"prague, czechia": "CZ",
	"budapest, hungary": "HU",
	"bucharest, romania": "RO",
	"kyiv, ukraine": "UA",
	"kiev, ukraine": "UA",
	"sao paulo, brazil": "BR",
	"rio de janeiro, brazil": "BR",
	"mexico city, mexico": "MX",
	"buenos aires, argentina": "AR",
	"bogota, colombia": "CO",
	"lima, peru": "PE",
	"santiago, chile": "CL",
	"jakarta, indonesia": "ID",
	"bangkok, thailand": "TH",
	"manila, philippines": "PH",
	"karachi, pakistan": "PK",
	"dhaka, bangladesh": "BD",
	"kathmandu, nepal": "NP",

	// Remote / Nomad tokens (when combined with country they still need a fallback)
	"remote": "??",
	"worldwide": "??",
	"nomad": "??",
	"digital nomad": "??",
	"earth": "??",
	"internet": "??",
	"everywhere": "??",
	"global": "??",
	"online": "??",
	"cyberspace": "??"
};

export const CDICT = {
	"afghanistan": "AF",
	"albania": "AL",
	"algeria": "DZ",
	"angola": "AO",
	"argentina": "AR",
	"australia": "AU",
	"austria": "AT",
	"bangladesh": "BD",
	"belgium": "BE",
	"brazil": "BR",
	"bulgaria": "BG",
	"myanmar": "MM",
	"burma": "MM",
	"cambodia": "KH",
	"cameroon": "CM",
	"canada": "CA",
	"sri lanka": "LK",
	"ceylon": "LK",
	"chile": "CL",
	"china": "CN",
	"colombia": "CO",
	"costa rica": "CR",
	"croatia": "HR",
	"cuba": "CU",
	"czech republic": "CZ",
	"czechia": "CZ",
	"denmark": "DK",
	"dominican republic": "DO",
	"ecuador": "EC",
	"egypt": "EG",
	"ethiopia": "ET",
	"finland": "FI",
	"france": "FR",
	"germany": "DE",
	"ghana": "GH",
	"greece": "GR",
	"guatemala": "GT",
	"haiti": "HT",
	"honduras": "HN",
	"hungary": "HU",
	"india": "IN",
	"indonesia": "ID",
	"iran": "IR",
	"iraq": "IQ",
	"ireland": "IE",
	"israel": "IL",
	"italy": "IT",
	"jamaica": "JM",
	"japan": "JP",
	"jordan": "JO",
	"kazakhstan": "KZ",
	"kenya": "KE",
	"south korea": "KR",
	"korea": "KR",
	"kuwait": "KW",
	"laos": "LA",
	"latvia": "LV",
	"lebanon": "LB",
	"libya": "LY",
	"lithuania": "LT",
	"malaysia": "MY",
	"mexico": "MX",
	"morocco": "MA",
	"nepal": "NP",
	"netherlands": "NL",
	"holland": "NL",
	"new zealand": "NZ",
	"nicaragua": "NI",
	"niger": "NE",
	"nigeria": "NG",
	"norway": "NO",
	"pakistan": "PK",
	"panama": "PA",
	"peru": "PE",
	"philippines": "PH",
	"poland": "PL",
	"portugal": "PT",
	"qatar": "QA",
	"romania": "RO",
	"russia": "RU",
	"russian federation": "RU",
	"rwanda": "RW",
	"saudi arabia": "SA",
	"senegal": "SN",
	"singapore": "SG",
	"slovakia": "SK",
	"slovenia": "SI",
	"somalia": "SO",
	"south africa": "ZA",
	"spain": "ES",
	"sudan": "SD",
	"sweden": "SE",
	"switzerland": "CH",
	"syria": "SY",
	"thailand": "TH",
	"turkey": "TR",
	"ukraine": "UA",
	"uganda": "UG",
	"united arab emirates": "AE",
	"uae": "AE",
	"united kingdom": "GB",
	"uk": "GB",
	"england": "GB",
	"scotland": "GB",
	"wales": "GB",
	"great britain": "GB",
	"united states": "US",
	"usa": "US",
	"u.s.a.": "US",
	"u.s.": "US",
	"america": "US",
	"uruguay": "UY",
	"venezuela": "VE",
	"vietnam": "VN",
	"viet nam": "VN",
	"yemen": "YE",
	"zambia": "ZM",
	"zimbabwe": "ZW",
	"estonia": "EE",
	"georgia": "GE",
	"iceland": "IS",
	"mongolia": "MN",
	"moldova": "MD",
	"montenegro": "ME",
	"north macedonia": "MK",
	"tanzania": "TZ",
	"mauritius": "MU",
	"bolivia": "BO",
	"bosnia": "BA",
	"botswana": "BW",
	"brunei": "BN",
	"burundi": "BI",
	"cape verde": "CV",
	"central african republic": "CF",
	"chad": "TD",
	"congo": "CG",
	"dr congo": "CD",
	"democratic republic of congo": "CD",
	"el salvador": "SV",
	"fiji": "FJ",
	"gabon": "GA",
	"gambia": "GM",
	"guinea": "GN",
	"guyana": "GY",
	"liberia": "LR",
	"mali": "ML",
	"mauritania": "MR",
	"mozambique": "MZ",
	"namibia": "NA",
	"sierra leone": "SL",
	"suriname": "SR",
	"tajikistan": "TJ",
	"togo": "TG",
	"trinidad": "TT",
	"trinidad and tobago": "TT",
	"tunisia": "TN",
	"uzbekistan": "UZ",
	"ivory coast": "CI",
	"côte d'ivoire": "CI",
	"cote d'ivoire": "CI",
	"new york": "US",
	"san francisco": "US",
	"sf": "US",
	"los angeles": "US",
	"la": "US",
	"chicago": "US",
	"seattle": "US",
	"boston": "US",
	"austin": "US",
	"dallas": "US",
	"denver": "US",
	"miami": "US",
	"portland": "US",
	"atlanta": "US",
	"washington dc": "US",
	"washington d.c.": "US",
	"dc": "US",
	"silicon valley": "US",
	"bay area": "US",
	"new york city": "US",
	"manhattan": "US",
	"brooklyn": "US",
	"san jose": "US",
	"palo alto": "US",
	"mountain view": "US",
	"sunnyvale": "US",
	"cambridge ma": "US",
	"new england": "US",
	"pacific northwest": "US",
	"london": "GB",
	"manchester": "GB",
	"birmingham": "GB",
	"edinburgh": "GB",
	"glasgow": "GB",
	"bristol": "GB",
	"leeds": "GB",
	"liverpool": "GB",
	"oxford": "GB",
	"cambridge": "GB",
	"sheffield": "GB",
	"belfast": "GB",
	"paris": "FR",
	"marseille": "FR",
	"lyon": "FR",
	"toulouse": "FR",
	"bordeaux": "FR",
	"nantes": "FR",
	"nice": "FR",
	"berlin": "DE",
	"munich": "DE",
	"münchen": "DE",
	"hamburg": "DE",
	"frankfurt": "DE",
	"cologne": "DE",
	"köln": "DE",
	"düsseldorf": "DE",
	"stuttgart": "DE",
	"toronto": "CA",
	"vancouver": "CA",
	"montreal": "CA",
	"calgary": "CA",
	"ottawa": "CA",
	"edmonton": "CA",
	"sydney": "AU",
	"melbourne": "AU",
	"brisbane": "AU",
	"perth": "AU",
	"adelaide": "AU",
	"auckland": "NZ",
	"wellington": "NZ",
	"tokyo": "JP",
	"osaka": "JP",
	"kyoto": "JP",
	"yokohama": "JP",
	"nagoya": "JP",
	"sapporo": "JP",
	"beijing": "CN",
	"shanghai": "CN",
	"shenzhen": "CN",
	"guangzhou": "CN",
	"hong kong": "HK",
	"chengdu": "CN",
	"hangzhou": "CN",
	"delhi": "IN",
	"bangalore": "IN",
	"hyderabad": "IN",
	"chennai": "IN",
	"new delhi": "IN",
	"bengaluru": "IN",
	"kolkata": "IN",
	"pune": "IN",
	"ahmedabad": "IN",
	"jaipur": "IN",
	"amsterdam": "NL",
	"rotterdam": "NL",
	"the hague": "NL",
	"stockholm": "SE",
	"gothenburg": "SE",
	"malmö": "SE",
	"malmo": "SE",
	"oslo": "NO",
	"bergen": "NO",
	"madrid": "ES",
	"barcelona": "ES",
	"seville": "ES",
	"valencia": "ES",
	"rome": "IT",
	"milan": "IT",
	"naples": "IT",
	"florence": "IT",
	"turin": "IT",
	"moscow": "RU",
	"saint petersburg": "RU",
	"st. petersburg": "RU",
	"cairo": "EG",
	"dubai": "AE",
	"abu dhabi": "AE",
	"riyadh": "SA",
	"jeddah": "SA",
	"tel aviv": "IL",
	"jerusalem": "IL",
	"istanbul": "TR",
	"ankara": "TR",
	"jakarta": "ID",
	"bali": "ID",
	"bangkok": "TH",
	"ho chi minh": "VN",
	"hanoi": "VN",
	"hcmc": "VN",
	"saigon": "VN",
	"manila": "PH",
	"cebu": "PH",
	"kuala lumpur": "MY",
	"kl": "MY",
	"seoul": "KR",
	"nairobi": "KE",
	"lagos": "NG",
	"abuja": "NG",
	"accra": "GH",
	"casablanca": "MA",
	"rabat": "MA",
	"addis ababa": "ET",
	"dar es salaam": "TZ",
	"mexico city": "MX",
	"guadalajara": "MX",
	"monterrey": "MX",
	"bogota": "CO",
	"bogotá": "CO",
	"lima": "PE",
	"santiago": "CL",
	"buenos aires": "AR",
	"sao paulo": "BR",
	"são paulo": "BR",
	"rio de janeiro": "BR",
	"prague": "CZ",
	"budapest": "HU",
	"kyiv": "UA",
	"kiev": "UA",
	"riga": "LV",
	"vilnius": "LT",
	"tallinn": "EE",
	"zurich": "CH",
	"geneva": "CH",
	"vienna": "AT",
	"brussels": "BE",
	"lisbon": "PT",
	"porto": "PT",
	"dublin": "IE",
	"athens": "GR",
	"sofia": "BG",
	"bratislava": "SK",
	"dhaka": "BD",
	"karachi": "PK",
	"lahore": "PK",
	"islamabad": "PK",
	"tehran": "IR",
	"baghdad": "IQ",
	"amman": "JO",
	"beirut": "LB",
	"tunis": "TN",
	"algiers": "DZ",
	"kampala": "UG",
	"dakar": "SN",
	"kinshasa": "CD",
	"colombo": "LK",
	"kathmandu": "NP",
	"tbilisi": "GE",
	...CDICT_EXTENDEED,
	...flagToCodeMap,
	...USA,
	...CANADA,
	...MADAGASCAR,
	...PORTUGAL,
	...CHINA,
	...SWEDEN,
	...GERMANY,
	...MALAWI,
	...MOROCCO,
	...NIGERIA,
	...PORTUGAL
};
