export const MADAGASCAR = {
	"madagascar": "MG",
	"antananarivo": "MG",
	"tana": "MG",
	"tananarive": "MG",
	"toamasina": "MG",
	"tamatave": "MG",
	"antsirabe": "MG",
	"mahajanga": "MG",
	"majunga": "MG",
	"fianarantsoa": "MG",
	"fianar": "MG",
	"toliara": "MG",
	"tulear": "MG",
	"antsiranana": "MG",
	"madagasikara": "MG",
	"itaosy": "MG",
	"diego suarez": "MG",
	"diego-suarez": "MG",
	"diego": "MG",
	"tolanaro": "MG",
	"tolagnaro": "MG",
	"fort dauphin": "MG",
	"fort-dauphin": "MG",
	"ambovombe": "MG",
	"sambava": "MG",
	"antalaha": "MG",
	"ambilobe": "MG",
	"ambanja": "MG",
	"moramanga": "MG",
	"andoany": "MG",
	"hell-ville": "MG",
	"hellville": "MG",
	"nosy be": "MG",
	"morondava": "MG",
	"fenoarivo atsinanana": "MG",
	"fenerive est": "MG",
	"fenerive": "MG",
	"tsiroanomandidy": "MG",
	"maroantsetra": "MG",
	"ihosy": "MG",
	"ambatondrazaka": "MG",
	"amboasary": "MG",
	"ambalavao": "MG",
	"manakara": "MG",
	"andilamena": "MG",
	"antsohihy": "MG",
	"ambositra": "MG",
	"vangaindrano": "MG",
	"ampanihy": "MG",
	"marovoay": "MG",
	"ambatofinandrahana": "MG",
	"mandritsara": "MG",
	"andapa": "MG",
	"soavinandriana": "MG",
	"ambatoboeny": "MG",
	"farafangana": "MG",
	"mahanoro": "MG",
	"ikongo": "MG",
	"bealanana": "MG",
	"mampikony": "MG",
	"betafo": "MG",
	"vavatenina": "MG",
	"ambodifototra": "MG",
	"ile sainte-marie": "MG",
	"sainte marie": "MG",
	"mananara avaratra": "MG",
	"mananara nord": "MG",
	"ambatolampy": "MG",
	"ankazobe": "MG",
	"maevatanana": "MG",
	"ambohadratrimo": "MG",
	"arivonimamo": "MG",
	"boriziny": "MG",
	"port-berge": "MG",
	"amparafaravola": "MG",
	"brickaville": "MG",
	"vohibinany": "MG",
	"morombe": "MG",
	"tsaratanana": "MG",
	"fandriana": "MG",
	"maintirano": "MG",
	"vohemar": "MG",
	"vohimarina": "MG",
	"anjozorobe": "MG",
	"manja": "MG",
	"mananjary": "MG",
	"betioky": "MG",
	"mahabo": "MG",
	"befandriana-avaratra": "MG",
	"befandriana nord": "MG",
	"miandrivazo": "MG",
	"manjakandriana": "MG",
	"betroka": "MG",
	"vatomandry": "MG",
	"vohipeno": "MG",
	"soalala": "MG",
	"ifanadiana": "MG",
	"miarinarivo": "MG",
	"analalava": "MG",
	"ambohimahasoa": "MG",
	"besalampy": "MG"
};
