export const PORTUGAL = {
	// English, Latin, & International Variations
	"Portugal": "PT",
	"Portugalia": "PT",
	"Lisbon": "PT",
	"Porto": "PT",
	"Oporto": "PT",
	"Braga": "PT",
	"Coimbra": "PT",
	"Funchal": "PT",
	"Ponta Delgada": "PT",
	"Faro": "PT",
	"Evora": "PT",
	"Setubal": "PT",
	"Aveiro": "PT",
	"Viseu": "PT",
	"Guimaraes": "PT",
	"Leiria": "PT",
	"Sintra": "PT",
	"Cascais": "PT",
	"Loures": "PT",
	"Amadora": "PT",
	"Almada": "PT",
	"Matosinhos": "PT",
	"Vila Nova de Gaia": "PT",
	"Maia": "PT",
	"Gondomar": "PT",
	"Santarem": "PT",
	"Castelo Branco": "PT",
	"Viana do Castelo": "PT",
	"Vila Real": "PT",
	"Braganca": "PT",
	"Beja": "PT",
	"Portalegre": "PT",
	"Angra do Heroismo": "PT",
	"Horta": "PT",
	"Portimao": "PT",
	"Albufeira": "PT",
	"Lagos": "PT",
	"Olhao": "PT",
	"Silves": "PT",
	"Tavira": "PT",
	"Quarteira": "PT",
	"Vilamoura": "PT",
	"Oeste": "PT",
	"Torres Vedras": "PT",
	"Caldas da Rainha": "PT",
	"Peniche": "PT",
	"Obidos": "PT",
	"Alcobaca": "PT",
	"Tomar": "PT",
	"Abrantes": "PT",
	"Fatima": "PT",
	"Ourem": "PT",
	"Figueira da Foz": "PT",
	"Marinha Grande": "PT",
	"Pombal": "PT",
	"Covilha": "PT",
	"Fundao": "PT",
	"Guarda": "PT",
	"Seia": "PT",
	"Lamego": "PT",
	"Chaves": "PT",
	"Mirandela": "PT",
	"Barcelos": "PT",
	"Famalicao": "PT",
	"Vila Nova de Famalicao": "PT",
	"Fafe": "PT",
	"Povoa de Varzim": "PT",
	"Vila do Conde": "PT",
	"Oliveira de Azemeis": "PT",
	"Sao Joao da Madeira": "PT",
	"Santa Maria da Feira": "PT",
	"Ovar": "PT",
	"Ilhavo": "PT",
	"Agueda": "PT",
	"Anadia": "PT",
	"Mealhada": "PT",
	"Cantanhede": "PT",
	"Montemor-o-Velho": "PT",
	"Elvas": "PT",
	"Estremoz": "PT",
	"Sines": "PT",
	"Santiago do Cacem": "PT",
	"Setubal Peninsula": "PT",
	"Barreiro": "PT",
	"Moita": "PT",
	"Seixal": "PT",
	"Montijo": "PT",
	"Alcochete": "PT",
	"Palmela": "PT",
	"Odivelas": "PT",
	"Vila Franca de Xira": "PT",
	"Mafra": "PT",
	"Oeiras": "PT",
	"Espinho": "PT",
	"Trofa": "PT",
	"Felgueiras": "PT",
	"Amarante": "PT",
	"Marco de Canaveses": "PT",
	"Penafiel": "PT",
	"Paredes": "PT",
	"Valongo": "PT",
	"Santo Tirso": "PT",
	"Vizela": "PT",
	"Esposende": "PT",
	"Ponte de Lima": "PT",
	"Valenca": "PT",
	"Moncao": "PT",
	"Caminha": "PT",
	"Arcos de Valdevez": "PT",
	"Ponte da Barca": "PT",
	"Espinho Coastal": "PT",
	"Macedo de Cavaleiros": "PT",
	"Miranda do Douro": "PT",
	"Peso da Regua": "PT",
	"Tarouca": "PT",
	"Mangualde": "PT",
	"Tondela": "PT",
	"Santa Comba Dao": "PT",
	"Gouveia": "PT",
	"Sabugal": "PT",
	"Trancoso": "PT",
	"Pinhel": "PT",
	"Meda": "PT",
	"Foz Coa": "PT",
	"Vila Nova de Foz Coa": "PT",
	"Serta": "PT",
	"Proenca-a-Nova": "PT",
	"Entroncamento": "PT",
	"Torres Novas": "PT",
	"Golega": "PT",
	"Cartaxo": "PT",
	"Almeirim": "PT",
	"Rio Maior": "PT",
	"Benavente": "PT",
	"Samora Correia": "PT",
	"Salvaterra de Magos": "PT",
	"Coruche": "PT",
	"Chamusca": "PT",
	"Ourique": "PT",
	"Odemira": "PT",
	"Mertola": "PT",
	"Serpa": "PT",
	"Moura": "PT",
	"Reguengos de Monsaraz": "PT",
	"Montemor-o-Novo": "PT",
	"Vendas Novas": "PT",
	"Vila Vicosa": "PT",
	"Borba": "PT",
	"Campo Maior": "PT",
	"Ponte de Sor": "PT",
	"Sardoal": "PT",
	"Constancia": "PT",
	"Macao": "PT",
	"Vila de Rei": "PT",
	"Oleiros": "PT",
	"Sines Industrial": "PT",
	"Vila Nova de Milfontes": "PT",
	"Zambujeira do Mar": "PT",
	"Troia": "PT",
	"Comporta": "PT",
	"Grandola": "PT",
	"Alcacer do Sal": "PT",
	"Lagoa": "PT",
	"Carvoeiro": "PT",
	"Monchique": "PT",
	"Aljezur": "PT",
	"Sagres": "PT",
	"Vila do Bispo": "PT",
	"Loule": "PT",
	"Vilamoura Marina": "PT",
	"Vale do Lobo": "PT",
	"Quinta do Lago": "PT",
	"Sao Bras de Alportel": "PT",
	"Olhao da Restauracao": "PT",
	"Fuzeta": "PT",
	"Monte Gordo": "PT",
	"Vila Real de Santo Antonio": "PT",
	"Castro Marim": "PT",
	"Alcoutim": "PT",
	"Machico": "PT",
	"Camara de Lobos": "PT",
	"Santa Cruz": "PT",
	"Canico": "PT",
	"Ribeira Brava": "PT",
	"Calheta": "PT",
	"Porto Moniz": "PT",
	"Sao Vicente": "PT",
	"Santana": "PT",
	"Porto Santo": "PT",
	"Vila Baleira": "PT",
	"Ribeira Grande": "PT",
	"Lagoa Azores": "PT",
	"Vila Franca do Campo": "PT",
	"Nordeste": "PT",
	"Povoacao": "PT",
	"Praia da Vitoria": "PT",
	"Velas": "PT",
	"Madalena": "PT",
	"Lajes do Pico": "PT",
	"Sao Roque do Pico": "PT",
	"Santa Cruz da Graciosa": "PT",
	"Santa Cruz das Flores": "PT",
	"Lajes das Flores": "PT",
	"Vila do Porto": "PT",
	"Corvo": "PT",

	// Local / Portuguese Distinct Names Only
	"Lisboa": "PT",
	"Évora": "PT",
	"Setúbal": "PT",
	"Guimarães": "PT",
	"Santarém": "PT",
	"Bragança": "PT",
	"Angra do Heroísmo": "PT",
	"Portimão": "PT",
	"Olhão": "PT",
	"Óbidos": "PT",
	"Alcobaça": "PT",
	"Fátima": "PT",
	"Ourém": "PT",
	"Covilhã": "PT",
	"Fundão": "PT",
	"Vila Nova de Famalicão": "PT",
	"Póvoa de Varzim": "PT",
	"Oliveira de Azeméis": "PT",
	"São João da Madeira": "PT",
	"Ílhavo": "PT",
	"Águeda": "PT",
	"Santiago do Cacém": "PT",
	"Valença": "PT",
	"Monção": "PT",
	"Peso da Régua": "PT",
	"Santa Comba Dão": "PT",
	"Mêda": "PT",
	"Vila Nova de Foz Côa": "PT",
	"Sertã": "PT",
	"Golegã": "PT",
	"Mértola": "PT",
	"Vila Viçosa": "PT",
	"Constância": "PT",
	"Mação": "PT",
	"Tróia": "PT",
	"Grândola": "PT",
	"Alcácer do Sal": "PT",
	"Loulé": "PT",
	"São Brás de Alportel": "PT",
	"Olhão da Restauração": "PT",
	"Fuseta": "PT",
	"Vila Real de Santo António": "PT",
	"Câmara de Lobos": "PT",
	"Caniço": "PT",
	"Lagoa Açores": "PT",
	"Praia da Vitória": "PT"
};
